(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.back01 = function() {
	this.initialize(img.back01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,385,250);


(lib.back02 = function() {
	this.initialize(img.back02);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.back03 = function() {
	this.initialize(img.back03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.back04 = function() {
	this.initialize(img.back04);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.LastFrame = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnmBbIAAhZIB4AAIAABqgApGBOIAAhMIBcAAIAABZgAH9AyQgLgRAAgfQAAggAMgSQAKgSAWAAQApAAAABCQAAAfgLASQgLASgWAAQgTAAgLgRgAIBACQABA0AbAAQAbAAgBg1QAAg3gaAAQgcAAAAA4gAFbA9IAAgQQAKAJANAAQASAAAAgNQAAgFgDgDQgEgEgMgFQgNgFgFgGQgEgGAAgJQgBgMAKgIQAJgHAOAAQALAAAJAEIAAAPQgJgHgMAAQgHAAgEAEQgFAEAAAFQAAAFAEAEQADADAKAFQANAFAGAGQAFAGABAKQAAAMgKAHQgJAIgQAAQgNAAgJgGgAB+A2QgMgNAAgWQAAgWANgNQAMgNAWAAQAVAAAMANQAMAMAAAWQAAAWgNANQgNAOgUAAQgVAAgNgNgACKgHQgJAJAAARQAAAQAJAKQAIAJAPAAQAOAAAHgJQAJgJgBgSQABgRgJgIQgHgKgOAAQgPAAgIAKgAAUA2QgKgMAAgVQAAgWALgOQAMgOAUAAQASAAAJAPIABAAIAAg6IAPAAIAACJIgPAAIAAgQIgBAAQgLASgVAAQgRAAgLgNgAAhgHQgIAJAAASQAAAQAIAJQAHAJANAAQAMAAAHgJQAJgJAAgNIAAgOQgBgKgHgIQgIgIgLAAQgNAAgIAKgAHQBBIAAhwQgFAEgJAFQgJAFgIACIAAgPQAKgDAMgGQAKgGAIgGIAFAAIAACEgAEpBBIgUhHIgBAAIgXBHIgOAAIgchcIAPAAIAVBKIABAAIAWhKIAOAAIAVBKIABAAIAUhKIAPAAIgcBcgAgVBBIAAg1QAAgdgWAAQgLAAgHAJQgHAIAAAMIAAA1IgPAAIAAhcIAPAAIAAAPQAKgRAVAAQAPAAAIAKQAIAKAAARIAAA5gAh4BBIAAhcIAOAAIAABcgAi7BBIgdhmIAAAAIgdBmIgSAAIgmiBIAQAAIAfBrIAAAAIAfhrIAPAAIAdBsIABAAIAdhsIAQAAIgkCBgAnmgBIAAhZIB4gRIAABqgApGgBIAAhMIBcgNIAABZgAh4gyQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDACQgDADgEAAQgEAAgDgCg");
	this.shape.setTransform(66.45,198.775);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgKAgIgIgCIgDgCIgBgEIAAgIIAKABIAIAAIAHgBQAAAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAgBIAAgBIgBgCIgDgBIgDgBIgJgDIgGgDQgCgBgBgDIgBgIQAAgHABgDQACgEADgDIAHgDIAJgBIALABIAGACIADACIABAEIAAAIIgMgBIgFAAIgGABQAAAAgBAAQAAABAAAAQAAABgBAAQAAABAAAAQAAABAAAAQABABAAAAQAAAAAAABQABAAAAAAIAFACIAJADQAEABACACIAEAFIABAIQAAAGgBAEQgCAEgDACQgDADgFABIgJABIgKgBg");
	this.shape_1.setTransform(225.075,77.975);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgUAoQgFgFAAgKQAAgGACgEQACgEAEgCQADgCAFgBIAJAAIAGAAIAAgEQAAgDgCgBIgHgBIgJABIgFAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAAAAAAAIgBgDIAAgIIAJgDIAMgBQAOAAAGAFQAGAGAAAKIAAApIgMAAIgCAAIgBgBIgCgBIAAgDIgBgBIgGAFQgDACgGAAQgJAAgEgFgAgGATQgBABAAAAQAAABAAAAQgBABAAAAQAAABAAABQAAAEACABIAFABQAEAAADgCIAAgLIgGAAQgEAAgCACgAgFgXQAAAAgBAAQAAAAAAgBQAAAAgBAAQAAAAAAgBIAAgCIAEgJIADgIIAPAAIACABIABACIgBACIgMAQg");
	this.shape_2.setTransform(219.175,76.675);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAbAgQgFAAAAgEIAAgkIgBgEQAAgBgBAAQAAAAAAAAQgBgBgBAAQAAAAgBAAIgEABIgDABIAAAsIgPAAQgEAAAAgEIAAgkIgBgEQAAgBgBAAQAAAAAAAAQgBgBgBAAQAAAAgBAAIgDABIgEABIAAAsIgPAAQgFAAAAgEIAAg6IALAAIAFABIABAEIABACQAFgEADgCQAEgCAFAAQAFAAADACQAEACACAEQADgEAFgCQAEgCAGAAQAQAAAAAVIAAAqg");
	this.shape_3.setTransform(211.35,77.925);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgJAfQgFgCgEgEQgDgEgCgGQgBgHAAgIQAAgRAGgHQAHgIANABQAHAAAFACQAEACADADQACADABAFIABALIAAADIAAACIgBAEIAAADIgeAAQAAAFADADQADACAFAAIAJAAIAGAAIADABIABADIAAAHIgIADQgGABgIABQgGgBgFgBgAAIgEQAAgIgBgDQgCgDgEAAQgDAAgCADQgCAEAAAHIAOAAIAAAAg");
	this.shape_4.setTransform(201.325,78);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgPAZQgGgIAAgRQAAgQAGgIQAGgIANABIAIAAIAGACIADACIABAFIAAAHIgIgBIgFAAIgFABIgEADIAAAEIAAAIIAAAIIAAAFQAAAAABABQAAAAAAABQABAAAAAAQABAAAAABIAFAAIACAAIACAAIACAAIACAAIAEABQABAAAAABQAAAAAAAAQABABAAAAQAAABAAAAIAAAIIgHAEIgLABQgNAAgGgIg");
	this.shape_5.setTransform(195.725,78);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgMAfQgFgCgDgEQgDgEgCgGQgBgHAAgIQAAgIABgGQACgGADgEQADgEAFgCQAGgBAGAAQAHAAAGABQAFACADAEQADAEACAGQABAGAAAIQAAAIgBAHQgCAGgDAEQgDAEgFACQgGACgHAAQgGAAgGgCgAgCgQIgDADIgBAEIAAAJIAAAJIABAGIADACIACAAIADAAIADgCIABgGIAAgJIAAgJIgBgEIgDgDIgDgBIgCABg");
	this.shape_6.setTransform(189.825,78);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAKAgQgEAAABgEIAAgkQgBgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAgBAAQAAgBgBAAQgBAAgBAAIgCABIgDABIAAAsIgQAAQgFAAAAgEIAAg6IAMAAIAEABIACAEIAAACQAFgEADgCQAEgCAFAAQASAAgBAVIAAAqg");
	this.shape_7.setTransform(183.4,77.925);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgMAfQgFgCgDgEQgDgEgCgGQgBgHAAgIQAAgIABgGQACgGADgEQADgEAFgCQAGgBAGAAQAHAAAGABQAFACADAEQADAEACAGQABAGAAAIQAAAIgBAHQgCAGgDAEQgDAEgFACQgGACgHAAQgGAAgGgCgAgCgQIgDADIgBAEIAAAJIAAAJIABAGIADACIACAAIADAAIADgCIABgGIAAgJIAAgJIgBgEIgDgDIgDgBIgCABg");
	this.shape_8.setTransform(176.925,78);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgHApQgFgCgEgFQgEgFgCgIQgCgIAAgNQAAgLACgJQACgIADgFQAEgFAGgCQAGgCAHAAIAJABQAEAAACACQAAAAABAAQAAAAABABQAAAAAAAAQABABAAAAIABAEIAAAJIgIgBIgHAAIgHABQgDABAAADIgCAIIgBAMIABAMIACAJQAAACADABIAGABIAHAAIAFAAQAEAAAAAFIAAAKIgJACIgMABQgFAAgGgCg");
	this.shape_9.setTransform(170.775,76.95);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#0096D6").s().p("AlTBkQgyAAAAgyIAAiVILZAAQAyAAAAAyIAACVg");
	this.shape_10.setTransform(197.7723,77.3,0.9526,1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#0096D6").s().p("AgDChIAfhaIAtAAQAHgBAFgDQAFgEACgGIAkhhQAFgLgHgKQgFgHgNgBIg/AAIhRDhQgbgFgWgPQgXgPgQgVQgRgVgKgZQgJgZAAgdQAAgaAJgaQAJgYAQgUQAQgVAUgPQAWgPAagGIhSDgIAhAAIAsh3IAaAAIgsB3IAjAAIAnhvQAEgLgGgKQgFgHgMgBIgdAAIAghbIAHAAQAhABAdANQAdALAXAXQAWAWANAcQAMAfAAAfQAAAhgMAeQgNAdgWAWQgXAWgdANQgdAMghAAgAAkAxIAjhhIAaAAIgjBhg");
	this.shape_11.setTransform(17.8784,17.906,1.1141,1.1141);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgIAJQgDgDAAgGQAAgFADgDQADgDAFAAQAGAAADADQADADAAAFQAAAGgDADQgDADgGAAQgFAAgDgDg");
	this.shape_12.setTransform(234.9,52.55);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgcAkQgKgLAAgZQAAgYAKgLQAIgMAUAAQAUAAAJAMQAKALAAAYQAAAZgKALQgJAMgUAAQgUAAgIgMgAgJgfQgDACgCADQgDAEgBAHQgBAHgBAIQABAKABAHQABAGADAEQACAEADACQAFABAEAAQAFAAAEgBQAEgCADgEIADgKIABgRIgBgPIgDgLQgDgDgEgCQgEgBgFgBQgEABgFABg");
	this.shape_13.setTransform(227.95,49);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgJA+IgHAAIgHgBIgFgCQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAAAgBIgBgDIAAgHIANABIAMABQAMAAAFgEQAFgEAAgIIAAgMIgKAGQgFACgHAAQgJAAgGgDQgGgEgEgFQgEgHgBgIQgBgGAAgKQAAgNACgJQADgJAFgGQAGgFAIgCQAIgCAKgBIAPABIANACIAFACQABAAAAAAQABABAAAAQAAABAAAAQAAABAAABIAAAHIgHAAIABAXIAAAWIAAAfQAAAQgJAIQgJAIgRAAgAgHguQgEACgDADQgDADgCAHQgBAGAAAJIABAPQABAEACAEQACAEAEABQAEACAEAAQAFAAAEgCIAIgEIAAg2IgGgBIgFAAIgLABg");
	this.shape_14.setTransform(218.725,50.55);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgEA/QgEAAAAgEIAAhWIANAAQAEAAAAADIAABXgAgHgsQgDgDAAgFQAAgFADgDQACgCAFAAQAGAAADACQACADAAAFQAAAFgCADQgDACgGAAQgFAAgCgCg");
	this.shape_15.setTransform(211.875,47.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgIA1QgGgGAAgMIAAg3IgGAAQgFAAAAgDIAAgKIAMAAIABgZIAMAAQAEAAAAAFIAAAUIARAAIADAAQAAABABAAQAAAAAAABQAAAAAAABQAAAAABAAIAAAKIgWAAIAAA2QAAAEABADQABADAFAAIAFAAIAEAAQAGAAAAAEIAAAIIgJACIgHAAQgMABgGgGg");
	this.shape_16.setTransform(206.7,47.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAXAvIgEgBIgBgDIAAg4QAAgJgEgFQgEgEgHAAQgHAAgFADIgIAGIAABFIgOAAQgEAAAAgEIAAhXIALAAIADABIACAEIAAAFQAMgMAQAAQAPAAAGAJQAGAIAAAOIAAA+g");
	this.shape_17.setTransform(198.925,48.925);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgcAkQgKgLABgZQgBgYAKgLQAIgMAUAAQAUAAAJAMQAJALAAAYQAAAZgJALQgJAMgUAAQgUAAgIgMgAgIgfQgEACgDADQgCAEgBAHQgCAHABAIQgBAKACAHQABAGACAEQADAEAEACQADABAFAAQAFAAAEgBQAEgCADgEIADgKIABgRIgBgPIgDgLQgDgDgEgCQgEgBgFgBQgFABgDABg");
	this.shape_18.setTransform(189.5,49);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgKAtQgHgEgFgGQgEgGgBgJQgDgIAAgMQABgYAIgLQAJgMARAAIANABIAJACIACADIABADIAAAIIgLgBIgJgBQgGAAgEACQgDABgDAEQgDAEgBAGQgCAGAAAJQAAAKACAGQACAHACADQADAEADABQAEACAFAAIAKgBIAHgBQAEAAAAAFIAAAHIgKADQgHACgHAAQgJAAgHgDg");
	this.shape_19.setTransform(181.1,49.025);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgcAoQgHgIAAgOQAAgIADgGQACgEAFgEQAFgDAGgBQAHgCAHABIASAAIAAgHQAAgJgFgDQgFgEgKAAIgPABIgIAAIgDgBIgBgCIAAgIIAOgDIAPgBQAKAAAHACQAHACAEAEQAEAEACAGQACAGAAAHIAAA9IgLAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAAAIgBgDIgBgGQgFAFgGADQgHAEgIgBQgOAAgHgHgAgJADQgEACgCACIgDAEIgBAHQAAAIAEAEQAEAEAJAAQAGAAAFgDQAFgDAEgDIAAgXIgSAAQgGAAgDABg");
	this.shape_20.setTransform(168.925,49);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgIA1QgGgGAAgMIAAg3IgGAAQgFAAABgDIAAgKIALAAIABgZIAMAAQADAAABAFIAAAUIARAAIADAAQAAABABAAQAAAAAAABQAAAAAAABQAAAAAAAAIAAAKIgVAAIAAA2QgBAEACADQACADAFAAIAEAAIAFAAQAEAAAAAEIAAAIIgIACIgHAAQgMABgGgGg");
	this.shape_21.setTransform(161.45,47.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgcA+QgFAAAAgEIAAg8IAAgVIABgWIgDAAQgEAAAAgEIAAgIIAHgBIAJgBIAKgBIAKgBQAKAAAJADQAIACAFAFQAGAGACAJQADAIAAAOQAAAXgIAMQgJALgRAAQgHAAgFgBIgJgEIAAAjgAgPguIAAA8IAIADIAIABQAFAAAEgBQAEgCADgEQACgDABgHIABgPIgBgPQgBgGgDgEQgDgEgFgCQgEgBgHAAIgGAAg");
	this.shape_22.setTransform(153.525,50.475);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgcAoQgHgIAAgOQAAgIADgGQACgEAFgEQAFgDAGgBQAHgCAHABIASAAIAAgHQAAgJgFgDQgFgEgKAAIgPABIgIAAIgDgBIgBgCIAAgIIAOgDIAPgBQAKAAAHACQAHACAEAEQAEAEACAGQACAGAAAHIAAA9IgLAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAAAIgBgDIgBgGQgFAFgGADQgHAEgIgBQgOAAgHgHgAgJADQgEACgCACIgDAEIgBAHQAAAIAEAEQAEAEAJAAQAGAAAFgDQAFgDAEgDIAAgXIgSAAQgGAAgDABg");
	this.shape_23.setTransform(144.325,49);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgdA1QgHgMAAgWQAAgZAJgLQAIgMASAAQAHAAAFACIAHADIAAgoIAPAAIACABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAB8IgLAAIgDgBQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIgBgFQgEAEgHAEQgGADgIAAQgRAAgHgMgAgHgNQgEACgCAEQgDAEgBAFIgBAQQAAARAEAIQADAHALAAQAGAAAFgCIAHgGIAAg2IgGgCIgJgBQgFAAgFACg");
	this.shape_24.setTransform(135.25,47.225);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgcAoQgHgIAAgOQAAgIADgGQACgEAFgEQAFgDAGgBQAHgCAHABIASAAIAAgHQAAgJgFgDQgFgEgKAAIgPABIgIAAIgDgBIgBgCIAAgIIAOgDIAPgBQAKAAAHACQAHACAEAEQAEAEACAGQACAGAAAHIAAA9IgLAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAAAIgBgDIgBgGQgFAFgGADQgHAEgIgBQgOAAgHgHgAgJADQgEACgCACIgDAEIgBAHQAAAIAEAEQAEAEAJAAQAGAAAFgDQAFgDAEgDIAAgXIgSAAQgGAAgDABg");
	this.shape_25.setTransform(126.025,49);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgNAuQgHgDgFgFQgFgGgDgJQgCgKAAgMQAAgMACgKQADgJAFgGQAEgGAHgCQAHgDAJAAQAKAAAHADQAGADAEAFQAEAFABAHQACAHAAAHIgBAKIgBAHIg0AAIACAMQABAFADAEQADACAFACQAEACAIgBIANgBIAIAAQAEAAAAAEIAAAHQgEACgIACQgHABgKAAQgJAAgIgCgAgHgfQgEACgCAEIgEAJIgBALIAlAAIAAgCIAAgDQAAgLgDgHQgEgFgKAAQgFAAgEACg");
	this.shape_26.setTransform(250.175,28.35);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgHAvIgIAAIgHgCIgFgBIgDgCIgBgDIAAgIIANABIAOABQALAAAEgDQAEgDAAgHIgBgFIgDgEIgGgDIgIgCIgMgEQgFgBgEgCQgEgDgCgEQgCgFAAgHQAAgOAJgHQAIgGAPAAIAGAAIAHABIAHABIAEACIADACIABADIAAAIIgOgCIgLAAQgJAAgEADQgEACAAAGIABAGIADADIAGADIAIACIAMADIAJAEQADADADAEQACAFAAAHQAAAIgDAFQgCAGgFADQgEAEgGABQgHACgGAAg");
	this.shape_27.setTransform(241.725,28.375);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgNAuQgHgDgFgFQgFgGgDgJQgCgKAAgMQAAgMACgKQADgJAFgGQAEgGAHgCQAHgDAJAAQAKAAAHADQAGADAEAFQAEAFABAHQACAHAAAHIgBAKIgBAHIg0AAIACAMQABAFADAEQADACAFACQAEACAIgBIANgBIAIAAQAEAAAAAEIAAAHQgEACgIACQgHABgKAAQgJAAgIgCgAgHgfQgEACgCAEIgEAJIgBALIAlAAIAAgCIAAgDQAAgLgDgHQgEgFgKAAQgFAAgEACg");
	this.shape_28.setTransform(229.725,28.35);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgUAsQgGgCgDgEQgDgEgCgGQgBgGgBgHIAAg9IAPAAIADABQAAABAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAA4QAAAJAEAEQADAEAJAAQAFAAAGgDQAFgCADgEIAAhEIAOAAQAEAAAAAEIAABXIgKAAIgEgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBAAAAgBIgBgFQgLAMgQAAQgIAAgEgDg");
	this.shape_29.setTransform(220.55,28.475);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AAUA+IgEgBIgBgDIAAghIgJAFQgGACgHAAQgQAAgIgLQgHgLAAgWQgBgOADgKQACgJAGgGQAFgFAJgCQAIgDALAAIAOABIAOACIAFABQAAAAABABQAAAAAAABQAAAAAAABQABABAAABIAAAHIgHAAIAAAWIABAVIAABAgAgHgtQgEABgDAEQgEAEgBAGQgCAHABAKQgBAJACAFQABAHACADQACAEADABQAEACAFAAQAFAAAEgCIAIgEIAAg6IgFAAIgGAAIgLABg");
	this.shape_30.setTransform(211.3,29.825);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgcAoQgHgIAAgNQAAgJADgGQACgEAFgEQAFgDAGgBQAHgCAHAAIASAAIAAgFQAAgKgFgEQgFgDgKAAIgPABIgIAAIgDAAIgBgDIAAgIIAOgEIAPgBQAKAAAHACQAHADAEAEQAEAEACAGQACAGAAAIIAAA8IgLAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBIgBgDIgBgFQgFAEgGAEQgHADgIABQgOAAgHgIgAgJAEQgEAAgCACIgDAGIgBAGQAAAIAEAEQAEAEAJAAQAGAAAFgDQAFgDAEgEIAAgWIgSAAQgGAAgDACg");
	this.shape_31.setTransform(198.225,28.35);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgKBBQgEAAAAgEIAAhXIAOAAQADABAAAEIAABWgAgLglQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgCIAFgMIAGgLIAOAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIgBADIgCACIgOAUg");
	this.shape_32.setTransform(192.475,26.45);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgJA+IgHAAIgHgCIgFgBQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAAAgBIgBgCIAAgIIANABIAMABQAMAAAFgEQAFgDAAgKIAAgLIgKAGQgFACgHAAQgJAAgGgEQgGgCgEgHQgEgGgBgHQgBgIAAgJQAAgOACgJQADgIAFgFQAGgGAIgCQAIgDAKABIAPABIANABIAFABQABABAAAAQAAABABAAQAAABAAAAQAAABAAABIAAAIIgHAAIABAWIAAAWIAAAfQAAAQgJAIQgJAJgRAAgAgHguQgEABgDAEQgDAEgCAFQgBAHAAAKIABANQABAGACADQACADAEACQAEACAEAAQAFAAAEgCIAIgEIAAg3IgGAAIgFAAIgLABg");
	this.shape_33.setTransform(185.375,29.9);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgdAlQgJgMAAgZQAAgYAJgMQAJgLAUAAQAUAAAJALQAKAMAAAYQAAAZgKAMQgJALgUAAQgUAAgJgLgAgJgfQgDACgCAEQgDAEgBAGQgBAHgBAIQABAKABAGQABAHADAEQACAEADABQAEACAFAAQAFAAAEgCQAEgBACgEIAEgLIABgQIgBgPIgEgKQgCgEgEgCQgEgCgFABQgFgBgEACg");
	this.shape_34.setTransform(175.85,28.35);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgFBAQgEgDgCgDQgCgDgBgFIgBgMIAAhmIAOAAIACABIABADIAABmQAAAGACABQACACAEgBIAEABQABABAAAAQAAAAAAABQABAAAAABQAAAAAAABIAAAJIgGABIgHAAQgFAAgDgBg");
	this.shape_35.setTransform(169.125,26.55);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgdAlQgIgMgBgZQABgYAIgMQAKgLATAAQAUAAAJALQAJAMAAAYQAAAZgJAMQgJALgUAAQgTAAgKgLgAgIgfQgEACgDAEQgCAEgBAGQgCAHAAAIQAAAKACAGQABAHACAEQADAEAEABQAEACAEAAQAFAAAEgCQAEgBACgEIAEgLIABgQIgBgPIgEgKQgCgEgEgCQgEgCgFABQgEgBgEACg");
	this.shape_36.setTransform(161.75,28.35);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AAXAvIgEgBIgBgDIAAg4QAAgJgEgFQgEgEgHAAQgHAAgFADIgIAGIAABFIgOAAQgEAAAAgEIAAhXIALAAIADABIACAEIAAAFQAMgMAQAAQAPAAAGAJQAGAIAAAOIAAA+g");
	this.shape_37.setTransform(152.325,28.275);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgKAtQgHgEgFgGQgEgGgBgJQgCgIAAgMQAAgYAJgLQAIgMASAAIAMABIAJACIACADIABADIAAAIIgLgBIgJgBQgGAAgEACQgDABgDAEQgDAEgBAGQgBAGAAAJQAAAKABAGQABAHADADQADAEADABQAEACAFAAIAKgBIAHgBQAFAAgBAFIAAAHQgEACgHABQgGACgHAAQgJAAgHgDg");
	this.shape_38.setTransform(143.95,28.375);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgNAuQgHgDgFgFQgFgGgDgJQgCgKAAgMQAAgMACgKQADgJAFgGQAEgGAHgCQAHgDAJAAQAKAAAHADQAGADAEAFQAEAFABAHQACAHAAAHIgBAKIgBAHIg0AAIACAMQABAFADAEQADACAFACQAEACAIgBIANgBIAIAAQAEAAAAAEIAAAHQgEACgIACQgHABgKAAQgJAAgIgCgAgHgfQgEACgCAEIgEAJIgBALIAlAAIAAgCIAAgDQAAgLgDgHQgEgFgKAAQgFAAgEACg");
	this.shape_39.setTransform(135.575,28.35);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgEA+QgEAAgBgEIAAhoIgdAAQgDAAAAgEIAAgLIBPAAIADABQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAABIAAALIghAAIAABsg");
	this.shape_40.setTransform(126.45,26.725);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgIAJQgDgDAAgGQAAgFADgCQACgEAGAAQAHAAACAEQADACAAAFQAAAGgDADQgCACgHABQgGgBgCgCg");
	this.shape_41.setTransform(265.75,11.25);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgcAkQgKgLABgZQgBgYAKgMQAIgLAUAAQAUAAAJALQAJAMAAAYQAAAZgJALQgJAMgUAAQgUAAgIgMgAgIgfQgEACgDADQgCAEgBAHQgCAGABAJQgBAKACAHQABAGACAEQADAEAEACQADABAFAAQAFAAAEgBQAEgCADgEIADgKIABgRIgBgPIgDgLQgDgDgEgCQgEgCgFAAQgFAAgDACg");
	this.shape_42.setTransform(258.8,7.7);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgdA1QgHgMAAgWQAAgZAJgLQAJgMARAAQAHAAAFACIAIADIAAgoIANAAIADABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAB8IgLAAIgDgBQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBIgBgFQgEAEgGAEQgHADgIAAQgQAAgIgMgAgHgNQgEACgCAEQgDAEgBAFIgBAQQAAARAEAIQAEAHAKAAQAGAAAFgCIAIgGIAAg2IgHgCIgJgBQgGAAgEACg");
	this.shape_43.setTransform(249.3,5.925);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgcAoQgHgIAAgOQAAgIADgFQACgFAFgDQAFgEAGgBQAHgCAHABIASAAIAAgHQAAgJgFgDQgFgEgKAAIgPABIgIABIgDgCIgBgDIAAgHIAOgDIAPgBQAKAAAHABQAHADAEAEQAEAEACAGQACAGAAAHIAAA9IgLAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBIgBgCIgBgGQgFAEgGAEQgHAEgIgBQgOABgHgIgAgJADQgEACgCACIgDAEIgBAHQAAAIAEAEQAEAEAJAAQAGAAAFgDQAFgDAEgDIAAgXIgSAAQgGAAgDABg");
	this.shape_44.setTransform(240.075,7.7);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AgIA1QgGgGAAgMIAAg2IgGAAQgEgBgBgEIAAgKIALAAIABgYIANAAQAEAAgBAFIAAATIASAAIADABQAAABABAAQAAAAAAABQAAAAAAABQABAAAAAAIAAALIgXAAIAAA1QAAAEACADQACADAEAAIAGAAIADAAQAGAAAAAEIAAAIIgIACIgIAAQgMABgGgGg");
	this.shape_45.setTransform(232.6,6.6);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgKAtQgHgEgFgGQgEgGgBgJQgCgIAAgMQAAgYAJgLQAIgMASAAIAMABIAJACIACADIABADIAAAIIgLgBIgJgBQgGAAgEACQgDABgDAEQgDAEgBAGQgBAGAAAJQAAAKABAGQABAHADADQADAEADABQAEACAFAAIAKgBIAHgBQAFAAgBAFIAAAHIgLADQgGACgHAAQgJAAgHgDg");
	this.shape_46.setTransform(225.85,7.725);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AgNAtQgHgCgFgGQgFgGgDgIQgCgKAAgNQAAgMACgIQADgKAFgGQAEgFAHgDQAHgDAJAAQAKAAAHADQAGADAEAFQAEAFABAHQACAHAAAIIgBAJIgBAHIg0AAIACAMQABAFADADQADADAFACQAEABAIABIANgBIAIgBQAEAAAAAEIAAAIQgEABgIABQgHACgKAAQgJAAgIgDgAgHgfQgEACgCADIgEAJIgBAMIAlAAIAAgDIAAgCQAAgMgDgFQgEgGgKAAQgFAAgEACg");
	this.shape_47.setTransform(217.475,7.7);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AAXAvIgEgBIgBgDIAAg4QAAgJgEgFQgEgEgHAAQgHAAgFADIgIAGIAABFIgOAAQgEAAAAgEIAAhXIALAAIADABIACAEIAAAFQAMgMAQAAQAPAAAGAJQAGAIAAAOIAAA+g");
	this.shape_48.setTransform(208.325,7.625);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgdAkQgIgLgBgZQABgYAIgMQAJgLAUAAQAUAAAJALQAKAMAAAYQAAAZgKALQgJAMgUAAQgUAAgJgMgAgJgfQgDACgCADQgDAEgBAHQgBAGgBAJQABAKABAHQABAGADAEQACAEADACQAFABAEAAQAFAAAEgBQAEgCACgEIAEgKIABgRIgBgPIgEgLQgCgDgEgCQgEgCgFAAQgEAAgFACg");
	this.shape_49.setTransform(198.9,7.7);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgKAtQgHgEgEgGQgFgGgCgJQgBgIAAgMQgBgYAKgLQAIgMASAAIALABIAJACIADADIABADIAAAIIgLgBIgJgBQgGAAgEACQgDABgDAEQgDAEgBAGQgCAGABAJQgBAKACAGQACAHACADQADAEADABQAEACAFAAIAKgBIAHgBQAFAAAAAFIAAAHIgMADQgGACgHAAQgJAAgHgDg");
	this.shape_50.setTransform(190.5,7.725);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgNAtQgHgCgFgGQgFgGgDgIQgCgKAAgNQAAgMACgIQADgKAFgGQAEgFAHgDQAHgDAJAAQAKAAAHADQAGADAEAFQAEAFABAHQACAHAAAIIgBAJIgBAHIg0AAIACAMQABAFADADQADADAFACQAEABAIABIANgBIAIgBQAEAAAAAEIAAAIQgEABgIABQgHACgKAAQgJAAgIgDgAgHgfQgEACgCADIgEAJIgBAMIAlAAIAAgDIAAgCQAAgMgDgFQgEgGgKAAQgFAAgEACg");
	this.shape_51.setTransform(178.525,7.7);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgSAuQgFAAAAgEIAAhXIALAAIAEABIABAEIABAIQAEgFAGgEQAGgEAIAAIAFABIABADIAAAMIgDAAIgCAAQgHAAgGACQgGACgFAHIAABAg");
	this.shape_52.setTransform(171.225,7.7);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AgcA+QgFAAAAgEIAAg8IAAgVIABgWIgDAAQgEAAAAgEIAAgIIAHgBIAJgBIAKgBIAKgBQAKAAAJADQAIACAFAFQAGAGACAJQADAIAAAOQAAAXgIAMQgJALgRAAQgHAAgFgBIgJgEIAAAjgAgPguIAAA8IAIADIAIABQAFAAAEgBQAEgCADgEQACgDABgHIABgPIgBgPQgBgGgDgEQgDgEgFgCQgEgBgHAAIgGAAg");
	this.shape_53.setTransform(162.925,9.175);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AAvAvQgEAAAAgEIAAg4QAAgJgDgFQgEgEgHAAQgHAAgFAEIgJAGIABAJIAAA7IgNAAIgDgBIgBgDIAAg4QAAgJgEgFQgEgEgHAAQgHAAgFADIgIAGIAABFIgNAAQgFAAAAgEIAAhXIALAAIAEABIABAEIABAFQAFgFAHgEQAGgDAJAAQAIAAAGADQAFADAEAHQAEgFAHgEQAHgEALAAQANAAAHAIQAHAHAAAQIAAA+g");
	this.shape_54.setTransform(151.175,7.625);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AgNAtQgHgCgFgGQgFgGgDgIQgCgKAAgNQAAgMACgIQADgKAFgGQAEgFAHgDQAHgDAJAAQAKAAAHADQAGADAEAFQAEAFABAHQACAHAAAIIgBAJIgBAHIg0AAIACAMQABAFADADQADADAFACQAEABAIABIANgBIAIgBQAEAAAAAEIAAAIQgEABgIABQgHACgKAAQgJAAgIgDgAgHgfQgEACgCADIgEAJIgBAMIAlAAIAAgDIAAgCQAAgMgDgFQgEgGgKAAQgFAAgEACg");
	this.shape_55.setTransform(139.475,7.7);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AgEA/QgEAAAAgEIAAhXIANAAQAEAAAAAEIAABXgAgHgtQgDgCAAgFQAAgFADgDQACgCAFAAQAGAAADACQACADAAAFQAAAFgCACQgDADgGAAQgFAAgCgDg");
	this.shape_56.setTransform(132.975,6);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AgTA/IgMgDIgEgCIAAgEIAAgJIANACIARABQAGAAAFgBQAFgCADgCQADgDABgDIABgIIgBgIQgBgEgDgCIgIgEIgLgFIgNgFQgGgCgEgEQgEgEgCgGQgDgGAAgIQAAgRAKgJQAKgIATAAIAPABIAMACIAEADIAAADIAAAJIgOgCIgOAAIgLABQgEABgDACIgEAFIgBAIQAAAFABADQABADADADIAIAEIALAEIANAGQAGACAEADQAEAEACAGQADAGAAAJQAAATgLAJQgKAIgTAAIgRgBg");
	this.shape_57.setTransform(126.325,6.075);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AGLB5IgDAAIgGgBQgBAAAAAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgCIANABIAGAAIAEgCIACgDIABgDIgBgEIgDgDIgDgBIgLgDIgEgCIgDgEIgBgFQAAgGAEgDQADgDAIAAIAGAAIADAAIADABQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAABIAAACIgGgBIgGAAIgFAAIgEACIgCACIAAAEIAAADIACACIAEACIALADIAEACIADAEQACACAAAEQAAAHgFADQgEADgIAAgAFYB2QgEgEAAgHQAAgHAFgEQAEgDAIAAIAMAAIAAgDIgBgFIgCgEIgEgBIgFgBIgIABIgEAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAgDIAHgBIAHAAIAJABIAFADQACACAAADIABAGIAAAfIgDAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgDIgCACIgEACIgEABIgEABQgIAAgDgEgAFfBiQAAAAgBABQAAAAgBAAQAAAAgBABQAAAAAAAAIgCAEIgBADQAAAGADACQADACAEAAQAFAAADgCQAEgBACgDIAAgOIgMAAIgGABgAEGB4QgEgBgCgDIgEgHIgBgLIABgLIAEgHIAFgEQAEgCAEAAQAFAAADACQAEABABADIADAGIAAAIIAAADIAAADIgdAAIABAIQABADACACQABACADABIAIABIAHAAIADgBIABABIABAAIAAADIgGABIgHABQgFAAgEgCgAEHBQQgCABgCADIgCAFIgBAHIAYAAIABgBIAAgCIgBgGQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBgBAAAAQgBAAAAgBQgBAAAAAAIgGgBQgEAAgCABgADfB5IgEAAIgGgBQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgCIANABIAGAAIAEgCIACgDIAAgDIgBgEIgCgDIgEgBIgKgDIgFgCIgDgEIgBgFQAAgGAEgDQAEgDAIAAIAFAAIAEAAIADABQAAAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAACIgGgBIgGAAIgGAAIgDACIgCACIgBAEIABADIACACIADACIALADIAFACIADAEQABACAAAEQAAAHgEADQgEADgIAAgACrB2QgDgEAAgHQAAgHAEgEQAFgDAIAAIALAAIAAgDIAAgFIgCgEIgEgBIgGgBIgHABIgFAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgDIAHgBIAHAAIAIABIAFADQACACABADIABAGIAAAfIgEAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgDIgDACIgDACIgEABIgFABQgHAAgEgEgACzBiQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAgBAAIgCAEIAAADQAAAGACACQADACAFAAQAEAAAEgCQADgBACgDIAAgOIgLAAIgGABgAAWB0QgEgGAAgMQAAgMAEgGQAEgGAKAAQAKAAAEAGQAEAGAAAMQAAAMgEAGQgEAGgKAAQgKAAgEgGgAAeBQQgCABgCACQgCACAAAEIgBAJIABAJQAAAEACACIAEADIAGABIAGgBIAEgDIACgGIABgJIgBgJQAAgEgCgCQgCgCgCgBIgGgBIgGABgAgJB4QgEgCgCgDQgCgDAAgEIgBgKQAAgMAEgGQAFgFAIAAIACAAIAGABIABAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAABIAAACIgFgBIgEAAIgGABQgCABgCACQgCACAAAEIgBAJIABAKIACAFQACADADAAIAFABIAFAAIADgBIABABIABAAIAAADIgGABIgFABQgFAAgDgCgAhBB5IgEAAIgGgBQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgCIANABIAGAAIAEgCIACgDIAAgDIgBgEIgCgDIgEgBIgKgDIgFgCIgDgEIgBgFQAAgGAEgDQAEgDAIAAIAFAAIAEAAIADABQAAAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAACIgGgBIgGAAIgGAAIgDACIgCACIgBAEIABADIACACIADACIALADIAFACIADAEQABACAAAEQAAAHgEADQgEADgIAAgAh1B2QgDgEAAgHQAAgHAEgEQAFgDAIAAIALAAIAAgDIAAgFIgCgEIgEgBIgGgBIgHABIgFAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgDIAHgBIAHAAIAIABIAFADQACACABADIABAGIAAAfIgEAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgDIgDACIgDACIgEABIgFABQgHAAgEgEgAhtBiQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAgBAAIgCAEIAAADQAAAGACACQADACAFAAQAEAAAEgCQADgBACgDIAAgOIgLAAIgGABgAjIB2QgDgEAAgHQAAgHAEgEQAFgDAIAAIALAAIAAgDIAAgFIgCgEIgEgBIgGgBIgHABIgFAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgDIAHgBIAHAAIAIABIAFADQACACABADIABAGIAAAfIgEAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgDIgDACIgDACIgEABIgFABQgHAAgEgEgAjABiQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAAAAAIgCAEIAAADQAAAGACACQADACAFAAQAEAAAEgCQADgBACgDIAAgOIgLAAIgGABgAj5B5IgEAAIgGgBQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgCIANABIAGAAIAEgCIACgDIAAgDIgBgEIgCgDIgEgBIgKgDIgFgCIgDgEIgBgFQAAgGAEgDQAEgDAIAAIAFAAIAEAAIADABQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAAACIgGgBIgGAAIgGAAIgDACIgCACIgBAEIABADIACACIADACIALADIAFACIADAEQABACAAAEQAAAHgEADQgEADgIAAgAkuB0QgEgGAAgMQAAgMAEgGQAEgGAKAAQAKAAAEAGQAEAGAAAMQAAAMgEAGQgEAGgKAAQgKAAgEgGgAkmBQQgCABgCACQgCACAAAEIgBAJIABAJQAAAEACACIAEADIAGABIAGgBIAEgDIACgGIABgJIgBgJQAAgEgCgCQgCgCgCgBIgGgBIgGABgAlpB4QgDgCgCgDIgDgHIAAgKQAAgNAEgFQAFgGAJAAIAHABIAFACIAAgVIADAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAAAIAABAIgEAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgDIgGAEQgDACgFAAQgFAAgDgCgAllBQQgCABgCACQgCACAAAEIgBAJQAAAKACAEQADAFAGAAIAFAAIADgCIAGgEIAAgeIgFgBIgGgBIgHABgAGpB4IAAgDIABgDIADgBIADABIABADIgBADIgDABIgEgBgAB3B5IgDgCIgBgDIgBgEIAAggIgEAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgDIAFAAIAAgMIAEAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAKIAKAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAADIgMAAIAAAiIABACIACABIAHAAIABAAIABABIAAADIgHAAIgFAAgAiJB3QgCgCAAgEIAAg5IAEAAIABABIAAA4IABADIADABIACAAIABAAIAAADIgFABQgDAAgCgCgAFHB5QgBAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgdQAAgGgDgDQgDgCgFAAIgEAAIgEACIgGAEIAAAkIgDAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgsIAEAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAADIAGgEIAEgBIAFgBQAHAAAEAEQAEAEAAAIIAAAfgACOB5QgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgsIAEAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAFIAGgEIAEgCIAEgBIACABIABABIAAADIgDAAQgEAAgDACIgHAFIAAAigABgB5QgBAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgdQAAgGgDgDQgDgCgFAAIgEAAIgEACIgGAEIAAAkIgDAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgsIAEAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAADIAGgEIAEgBIAFgBQAHAAAEAEQAEAEAAAIIAAAfgAlBB5QAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgsIADAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAAsgAl9B5IgBgCIgEgRIgZAAIgEATIgDAAQgBAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAEgUIAFgSIAJgXIAFAAIABABIAFAKIAFAPIAEARIAEAUgAmDBhIgFgRIgGgQIgHAQIgFARIAXAAIAAAAgAkjBFIAAgBIAGgLIAFAAIAAACIgHAKgAE8BDIgEgCIgCgCIgDAAIgBAAIgBABIAAACIAAACIgDAAIgBAAIAAgBQAAgEACgCQAAgBABAAQAAAAABgBQAAAAABAAQAAAAABAAIAEABIAGAEIADAAIABAAIABgBIAAgCIAAgCIADAAIABAAIAAABQAAAEgCACQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAIgEgBgAlDBCQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIABgDIADgBIADABQAAAAAAABQAAAAABAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAIgDABIgDgBgAF+AcQgFgGAAgMQAAgMAFgFQAEgGAKAAQAJAAAFAGQAEAFAAAMQAAAMgEAGQgFAFgJAAQgKAAgEgFgAGGgIQgDABgBADQgCACgBADIgBAJIABAJQABADACADIAEADIAGABIAFgBIAFgDIACgGIABgJIgBgJQgBgDgBgCIgFgEIgFgBIgGABgAEuAgQgEgBgCgDIgEgHIgBgLIABgKIAEgIIAFgEQAEgBAEAAQAFAAADABQAEACABACIADAGIAAAHIAAAEIAAADIgdAAIABAHQABAEACACQABACADABIAIABIAHgBIADAAIABAAIABABIAAACIgGACIgHAAQgFAAgEgBgAEvgHQgCABgCACIgCAFIgBAGIAYAAIABgBIAAgBIgBgFQAAgBAAgBQAAAAAAgBQgBAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBgBAAAAQgBAAAAgBIgGgBQgEAAgCACgAC+AhIgDAAIgGgBQgBAAAAgBQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAgDIANACIAGgBIAEgCIACgCIABgEIgBgEIgDgCIgDgCIgLgDIgEgCIgDgDIgBgFQAAgFAEgEQADgDAIAAIAGAAIADABIADABQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAADIgGgBIgGAAIgFAAIgEABIgCADIAAADIAAACIACADIAEABIALADIAEACIADAEQACADAAADQAAAHgFADQgEADgIAAgABMAcQgFgGAAgMQAAgMAFgFQAEgGAKAAQAJAAAFAGQAEAFAAAMQAAAMgEAGQgFAFgJAAQgKAAgEgFgABUgIQgDABgBADQgCACgBADIgBAJIABAJQABADACADIAEADIAGABIAFgBIAFgDIACgGIABgJIgBgJQgBgDgBgCIgFgEIgFgBIgGABgAAiAfQgDgBgCgDIgDgIIAAgJQAAgMAEgGQAFgFAJAAIAHABIAFACIAAgVIADAAQABAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAA+IgEAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgEIgGAEQgDACgFAAQgFAAgDgCgAAmgIQgCABgCADQgCACAAADIgBAIQAAAKACAFQADAFAGAAIAFgBIADgBIAGgEIAAgdIgFgCIgGgBIgHABgAGpAgIAAgEIABgDIADgBIADABIABADIgBAEIgDABIgEgBgAFnAeQgCgCAAgEIAAg3IAEAAIABABIAAA2IABAEIAEAAIACAAIABABIAAADIgFABQgEAAgCgDgAFSAeQgCgCAAgEIAAg3IAEAAIABABIAAA2IABAEIAEAAIACAAIABABIAAADIgFABQgEAAgCgDgAEUAgQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAgcIgeAAIAAAdIgDAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAg8IAEAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAAbIAeAAIAAgcIAEAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAA8gACbAgIgBAAIAAgBIgKghIgKAiIgEAAIgCAAIAAgBIgEgLIgIggIAEAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAHAdIADAJIAKgkIAEAAIACACIAKAiIAKgnIADAAIABAAIABABIgJAhIgEAKgAALAgQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgdQAAgFgDgDQgDgDgEAAIgEABIgEABIgFAFIAAAiIgEAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgrIADAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAEIAFgEIAFgBIAEgBQAGAAAEAEQAEADAAAIIAAAegAgiAgQAAAAgBAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAgrIADAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAArgAg/AgIgCAAIAAgBIgMgwIgMAxIgEAAIgBAAIgBgBIgFgPIgJgtIAFAAQAAAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIACAOIAJAnIAMgxIAFAAQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAMAwIAEgNIAIgpIADAAIACAAIAAABIgCAPIgMAtgAgkgWQAAAAAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIABgCIADgBIADABIABACQAAABAAAAQAAABgBAAQAAABAAAAQAAAAAAAAIgDABIgDgBgAFag4QgEgBgCgDIgEgHIgBgLIABgLIAEgHIAFgEQAEgCAEAAQAFAAADACQAEABABADIADAGIAAAIIAAADIAAADIgdAAIABAIQABADACACQABACADABIAIABIAHAAIADgBIABABIABAAIAAADIgGABIgHABQgFAAgEgCgAFbhgQgCABgCADIgCAFIgBAHIAYAAIABgBIAAgCIgBgGQAAAAAAgBQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQgBgBAAAAQgBAAAAgBQgBAAAAAAIgGgBQgEAAgCABgAEIg8QgFgGAAgMQAAgMAFgGQAEgGAKAAQAJAAAFAGQAEAGAAAMQAAAMgEAGQgFAGgJAAQgKAAgEgGgAEQhgQgDABgBACQgCACgBAEIgBAJIABAJQABAEACACIAEADIAGABIAFgBIAFgDIACgGIABgJIgBgJQgBgEgBgCIgFgDIgFgBIgGABgADig4QgEgDgDgEQgCgEgBgGIgBgNIABgPQABgGADgEQACgEAFgCQAEgBAGAAIAEAAIAJABIABACIAAADIgGgBIgHAAIgIABQgEABgCADQgCADgBAFIgBANIABAOIAEAJQACADADABIAIABIAHgBIAFgBQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAACIgGACIgIABQgGAAgFgCgABhg4QgEgBgCgDIgEgHIgBgLIABgLIAEgHIAFgEQAEgCAEAAQAFAAADACQAEABABADIADAGIAAAIIAAADIAAADIgdAAIABAIQABADACACQABACADABIAIABIAHAAIADgBIABABIABAAIAAADIgGABIgHABQgFAAgEgCgABihgQgCABgCADIgCAFIgBAHIAYAAIABgBIAAgCIgBgGQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBgBAAAAQgBAAAAgBQgBAAAAAAIgGgBQgEAAgCABgAhhg8QgEgGAAgMQAAgMAEgGQAEgGAKAAQAKAAAEAGQAEAGAAAMQAAAMgEAGQgEAGgKAAQgKAAgEgGgAhZhgQgCABgCACQgCACAAAEIgBAJIABAJQAAAEACACIAEADIAGABIAGgBIAEgDIACgGIABgJIgBgJQAAgEgCgCIgEgDIgGgBIgGABgAiLg4QgDgCgCgDIgCgHIgBgKQAAgNAFgFQAFgGAIAAIAIABIAEACIAAgVIAEAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAABAIgDAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgDIgFAEQgEACgFAAQgFAAgDgCgAiGhgQgDABgBACQgCACgBAEIgBAJQAAAKADAEQACAFAHAAIAEAAIAEgCIAFgEIAAgeIgFgBIgGgBIgGABgAi8g6QgDgEAAgHQAAgHAEgEQAFgDAIAAIALAAIAAgDIAAgFIgCgEIgEgBIgGgBIgHABIgFAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgDIAHgBIAHAAIAIABIAFADQACACABADIABAGIAAAfIgEAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgDIgDACIgDACIgEABIgFABQgHAAgEgEgAi0hOQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAgBAAIgCAEIAAADQAAAGACACQADACAFAAQAEAAAEgCQADgBACgDIAAgOIgLAAIgGABgAjbg3IgDAAIgGgBQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgCIANABIAGAAIAEgCIACgDIABgDIgBgEIgDgDIgDgBIgLgDIgEgCIgDgEIgBgFQAAgGAEgDQADgDAIAAIAGAAIADAAIADABQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABIAAACIgGgBIgGAAIgFAAIgEACIgCACIAAAEIAAADIACACIAEACIALADIAEACIADAEQACACAAAEQAAAHgFADQgEADgIAAgAkHg4QgDgBgDgDIgDgHIgBgLIABgLIADgHIAGgEQADgCAFAAQAFAAADACQADABACADIACAGIABAIIAAADIgBADIgcAAIABAIQAAADACACQACACADABIAHABIAHAAIAEgBIABABIAAAAIAAADIgFABIgIABQgFAAgEgCgAkFhgQgDABgBADIgDAFIAAAHIAYAAIAAgBIAAgCIAAgGQAAAAgBgBQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAgBgBQAAAAgBAAIgFgBQgEAAgCABgAktg4QgEgCgCgDQgCgDAAgEIgBgKQAAgMAEgGQAFgFAIAAIADAAIAGABIABAAQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABIAAACIgFgBIgFAAIgGABQAAAAgBABQAAAAgBAAQAAABgBAAQAAABgBAAQgCACAAAEIgBAJIABAKIACAFQACADADAAIAFABIAGAAIADgBIABABIABAAIAAADIgGABIgGABQgFAAgDgCgAlgg8QgFgGAAgMQAAgMAFgGQAEgGAKAAQAJAAAFAGQAEAGAAAMQAAAMgEAGQgFAGgJAAQgKAAgEgGgAlYhgQgDABgBACQgCACgBAEIgBAJIABAJQABAEACACIAEADIAGABIAFgBIAFgDIACgGIABgJIgBgJQgBgEgBgCIgFgDIgFgBIgGABgACFg5QgCgCAAgEIAAg5IAEAAIABABIAAA4IABADIAEABIACAAIABAAIAAADIgFABQgEAAgCgCgABCg3IgDgCIgBgDIgBgEIAAggIgEAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgDIAFAAIAAgMIAEAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAKIAKAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAADIgMAAIAAAiIABACIACABIAHAAIABAAIABABIAAADIgHAAIgFAAgAE0g3QAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgsIADAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAAFIAFgEIAEgCIAEgBIADABIAAABIAAADIgCAAQgFAAgDACIgGAFIAAAigAArg3QAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgdQAAgGgDgDQgDgCgFAAIgEAAIgEACIgGAEIAAAkIgDAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgsIAEAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAADIAGgEIAEgBIAFgBQAHAAAEAEQAEAEAAAIIAAAfgAgDg3QgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAg9IAEAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAABIAAA9gAg0g3QgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgsIAEAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAFIAGgEIAEgCIAEgBIACABIABABIAAADIgDAAQgEAAgDACIgHAFIAAAigAmAg3QAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgsIADAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAAFIAFgEIAEgCIAEgBIADABIAAABIAAADIgCAAQgFAAgDACIgGAFIAAAigAmwg3QAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAg8IARgBQALAAAFAFQAFAEAAALQAAAGgCADIgDAHIgGADIgIABIgGAAIgIgCIAAAZgAmshxIAAAdIANABIAGAAIAFgDQACgCAAgDIABgHIgBgIIgDgFIgFgCIgGAAgACbhYQgFgFAAgJQAAgJAFgFQAFgFAIAAQAJAAAFAFQAFAFAAAJQAAAJgFAFQgFAFgJAAQgIAAgFgFgACdhxQgDAEAAAHQAAAHADAFQAEAEAHAAQAIAAAEgEQADgFAAgHQAAgHgDgEQgEgFgIAAQgHAAgEAFgAGwhUQgBAAAAAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIAAgNIgBgOIgIAUIgCAAIgCgBIgIgTIgBAcIgDAAIgBgBIABghIAFAAQAAAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAIATIAJgVIAEAAQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIABAggAGEhUQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAAgdIgJAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAgDIAYAAQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABIAAACIgKAAIAAAegACuhdIgBAAIgBAAIgEgHIgDAAIAAAHIgCAAIgBgBIAAgRIABgBIAGAAQADAAACACQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABIgBAEIgCABIABACIADAFIAAABgAClhtIAAAGIADAAIADgBIABgCIgBgDIgDAAIgBAAg");
	this.shape_58.setTransform(223.925,202.975);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.LastFrame, new cjs.Rectangle(0,-7.7,270.2,222.89999999999998), null);


(lib.fondo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#FFFFFF","rgba(255,255,255,0)"],[0.325,1],-0.1,-34.5,-0.1,34.4).s().p("A+EFZIAAqxMA8JAAAIAAKxg");
	this.shape.setTransform(1092.525,33.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_1
	this.instance = new lib.back01();
	this.instance.setTransform(900,0);

	this.instance_1 = new lib.back04();

	this.instance_2 = new lib.back03();
	this.instance_2.setTransform(300,0);

	this.instance_3 = new lib.back02();
	this.instance_3.setTransform(600,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.fondo, new cjs.Rectangle(0,-1,1285,251), null);


(lib.copy03 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgIAJQgDgDAAgGQAAgFADgCQACgEAGAAQAGAAADAEQADACAAAFQAAAGgDADQgDACgGABQgGgBgCgCg");
	this.shape.setTransform(106.25,66.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgHAvIgIAAIgHgCIgFgBIgDgCIgBgDIAAgIIANABIAOABQALAAAEgDQAEgDAAgHIgBgFIgDgEIgGgDIgIgCIgMgEQgFgBgEgCQgEgDgCgEQgCgFAAgHQAAgOAJgHQAIgGAPAAIAGAAIAHABIAHABIAEACIADACIABADIAAAIIgOgCIgLAAQgJAAgEADQgEACAAAGIABAGIADADIAGADIAIACIAMADIAJAEQADADADAEQACAFAAAHQAAAIgDAFQgCAGgFADQgEAEgGABQgHACgGAAg");
	this.shape_1.setTransform(100.025,63.075);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgcAoQgHgIAAgOQAAgIADgFQACgFAFgDQAFgEAGgBQAHgCAHABIASAAIAAgHQAAgJgFgDQgFgEgKAAIgPABIgIABIgDgCIgBgDIAAgHIAOgDIAPgBQAKAAAHACQAHACAEAEQAEAEACAGQACAGAAAHIAAA9IgLAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAAAIgBgDIgBgGQgFAEgGAEQgHAEgIgBQgOABgHgIgAgJADQgEACgCACIgDAEIgBAHQAAAIAEAEQAEAEAJAAQAGAAAFgDQAFgDAEgDIAAgXIgSAAQgGAAgDABg");
	this.shape_2.setTransform(91.425,63.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgKBBQgEAAAAgEIAAhXIAOAAQADAAAAAEIAABXgAgLglQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIAAgEIAFgLIAGgLIAOAAQAAAAABAAQABAAAAABQAAAAABAAQAAABAAAAIgBADIgCADIgOATg");
	this.shape_3.setTransform(85.675,61.15);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgdA1QgHgMAAgWQAAgZAJgLQAJgMARAAQAHAAAFACIAIADIAAgoIANAAIADABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAB8IgLAAIgEgBQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBIgBgFQgEAEgGAEQgHADgIAAQgRAAgHgMgAgHgNQgEACgCAEQgDAEgBAFIgBAQQAAARAEAIQAEAHAKAAQAGAAAFgCIAIgGIAAg2IgHgCIgJgBQgGAAgEACg");
	this.shape_4.setTransform(78.3,61.275);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgHAvIgIAAIgHgCIgFgBIgDgCIgBgDIAAgIIANABIAOABQALAAAEgDQAEgDAAgHIgBgFIgDgEIgGgDIgIgCIgMgEQgFgBgEgCQgEgDgCgEQgCgFAAgHQAAgOAJgHQAIgGAPAAIAGAAIAHABIAHABIAEACIADACIABADIAAAIIgOgCIgLAAQgJAAgEADQgEACAAAGIABAGIADADIAGADIAIACIAMADIAJAEQADADADAEQACAFAAAHQAAAIgDAFQgCAGgFADQgEAEgGABQgHACgGAAg");
	this.shape_5.setTransform(66.125,63.075);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgcAkQgJgLAAgZQAAgYAJgMQAIgLAUAAQAUAAAJALQAJAMAAAYQAAAZgJALQgJAMgUAAQgUAAgIgMgAgIgfQgEACgDADQgCAEgBAHQgBAGAAAJQAAAKABAHQABAGACAEQADAEAEACQAEABAEAAQAFAAAEgBQAEgCADgEIADgKIABgRIgBgPIgDgLQgDgDgEgCQgEgCgFAAQgEAAgEACg");
	this.shape_6.setTransform(57.45,63.05);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgFA/QgEgCgCgDQgCgDgBgFIgBgNIAAhlIAOAAIACABIABADIAABnQAAAEACACQACACAEAAIAEABQABAAAAAAQAAAAAAABQABAAAAABQAAAAAAABIAAAIIgGABIgHABQgFAAgDgCg");
	this.shape_7.setTransform(50.725,61.25);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgHAvIgIAAIgHgCIgFgBIgDgCIgBgDIAAgIIANABIAOABQALAAAEgDQAEgDAAgHIgBgFIgDgEIgGgDIgIgCIgMgEQgFgBgEgCQgEgDgCgEQgCgFAAgHQAAgOAJgHQAIgGAPAAIAGAAIAHABIAHABIAEACIADACIABADIAAAIIgOgCIgLAAQgJAAgEADQgEACAAAGIABAGIADADIAGADIAIACIAMADIAJAEQADADADAEQACAFAAAHQAAAIgDAFQgCAGgFADQgEAEgGABQgHACgGAAg");
	this.shape_8.setTransform(40.475,63.075);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgcAkQgJgLAAgZQAAgYAJgMQAIgLAUAAQAUAAAJALQAJAMAAAYQAAAZgJALQgJAMgUAAQgUAAgIgMgAgIgfQgEACgDADQgCAEgBAHQgBAGAAAJQAAAKABAHQABAGACAEQADAEAEACQAEABAEAAQAFAAAEgBQAEgCADgEIADgKIABgRIgBgPIgDgLQgDgDgEgCQgEgCgFAAQgEAAgEACg");
	this.shape_9.setTransform(31.8,63.05);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgdA1QgHgMAAgWQAAgZAJgLQAIgMASAAQAHAAAFACIAHADIAAgoIAPAAIACABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAB8IgLAAIgDgBQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBIgBgFQgEAEgHAEQgGADgIAAQgRAAgHgMgAgHgNQgEACgCAEQgDAEgBAFIgBAQQAAARAEAIQADAHALAAQAGAAAFgCIAHgGIAAg2IgGgCIgJgBQgFAAgFACg");
	this.shape_10.setTransform(22.3,61.275);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgcAkQgJgLAAgZQAAgYAJgMQAIgLAUAAQAUAAAJALQAJAMAAAYQAAAZgJALQgJAMgUAAQgUAAgIgMgAgIgfQgEACgDADQgCAEgBAHQgBAGAAAJQAAAKABAHQABAGACAEQADAEAEACQADABAFAAQAFAAAEgBQAEgCADgEIADgKIABgRIgBgPIgDgLQgDgDgEgCQgEgCgFAAQgFAAgDACg");
	this.shape_11.setTransform(13,63.05);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgIA1QgGgGAAgMIAAg2IgGAAQgFgBAAgEIAAgKIAMAAIABgYIAMAAQAEAAAAAFIAAATIARAAIADABQAAABABAAQAAAAAAABQAAAAAAABQAAAAABAAIAAALIgWAAIAAA1QAAAEABADQABADAFAAIAGAAIADAAQAGAAAAAEIAAAIIgJACIgHAAQgMABgGgGg");
	this.shape_12.setTransform(5.1,61.95);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgcAlQgKgMABgZQgBgYAKgLQAJgMATAAQAUAAAJAMQAKALgBAYQABAZgKAMQgJALgUAAQgTAAgJgLgAgJgfQgDABgDAFQgCAEgBAGQgCAGABAJQgBAKACAGQABAHACAEQADAEADABQAEACAFAAQAFAAAEgCQAEgBADgEIADgLIABgQIgBgPIgDgKQgDgFgEgBQgEgCgFABQgFgBgEACg");
	this.shape_13.setTransform(141.9,42.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAvAvQgEAAAAgEIAAg4QAAgJgDgFQgEgEgHAAQgHAAgFAEIgJAGIABAJIAAA7IgNAAIgDgBIgBgDIAAg4QAAgJgEgFQgEgEgHAAQgHAAgFADIgIAGIAABFIgNAAQgFAAAAgEIAAhXIALAAIAEABIABAEIABAFQAFgFAHgEQAGgDAJAAQAIAAAGADQAFADAEAHQAEgFAHgEQAHgEALAAQANAAAHAIQAHAHAAAQIAAA+g");
	this.shape_14.setTransform(129.975,42.325);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgEA/QgEAAAAgEIAAhWIANAAQAEAAAAADIAABXgAgHgsQgDgCAAgGQAAgFADgDQACgCAFAAQAGAAADACQACADAAAFQAAAGgCACQgDACgGAAQgFAAgCgCg");
	this.shape_15.setTransform(120.675,40.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAXAuQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAAAIgBgDIgIgSQgFgIgGgJQgIAKgFAKIgIATIgMAAIgDgBQAAAAgBAAQAAAAAAgBQAAAAAAgBQgBAAAAgBIABgEQAFgKAHgKQAGgKAIgIIgHgKIgIgLIgHgMIgFgMIAQAAIADABIACADIAEAJIAEAIIAEAHIAFAIQAGgHAFgKQAGgJADgKIAMAAIAEABIABACIAAACIgCADIgEAJIgHAKIgGAJIgHAIQALALAHANQAHAMADALg");
	this.shape_16.setTransform(114.4,42.425);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgcA6QgHgIAAgNQAAgJADgFQACgGAFgDQAFgEAGgBQAHgBAHAAIASAAIAAgGQAAgJgFgDQgFgEgKAAIgPABIgIABIgDgBIgBgDIAAgIIAOgDIAPgBQAKAAAHACQAHACAEAEQAEAEACAGQACAGAAAHIAAA9IgLAAQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAIgBgDIgBgGQgFAFgGADQgHAEgIAAQgOAAgHgIgAgJAWQgEABgCACIgDAFIgBAGQAAAIAEAEQAEAEAJAAQAGAAAFgDQAFgDAEgDIAAgXIgSAAQgGAAgDACgAgEgmQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAgBAAIABgDIAFgMIAFgLIAOAAQABAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAACIgCADIgPATg");
	this.shape_17.setTransform(105.425,40.575);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAvAvQgEAAAAgEIAAg4QAAgJgDgFQgEgEgHAAQgHAAgFAEIgJAGIABAJIAAA7IgNAAIgDgBIgBgDIAAg4QAAgJgEgFQgEgEgHAAQgHAAgFADIgIAGIAABFIgNAAQgFAAAAgEIAAhXIALAAIAEABIABAEIABAFQAFgFAHgEQAGgDAJAAQAIAAAGADQAFADAEAHQAEgFAHgEQAHgEALAAQANAAAHAIQAHAHAAAQIAAA+g");
	this.shape_18.setTransform(93.925,42.325);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgUAsQgGgCgDgEQgDgEgCgGQgBgGgBgHIAAg9IAPAAIADABQAAABAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAA4QAAAJAEAEQADAEAJAAQAFAAAGgDQAFgCADgEIAAhEIAOAAQAEAAAAAEIAABXIgKAAIgEgBQAAgBgBAAQAAAAAAgBQAAAAAAgBQgBAAAAgBIgBgFQgLAMgQAAQgIAAgEgDg");
	this.shape_19.setTransform(78.35,42.525);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgIA1QgGgGAAgNIAAg2IgGAAQgEAAgBgDIAAgKIALAAIABgYIANAAQAEAAgBADIAAAVIASAAIADABQAAAAABAAQAAAAAAABQAAAAAAABQABAAAAABIAAAJIgXAAIAAA2QABAFABADQACACAEAAIAGAAIADAAQAFAAABAEIAAAJIgIABIgIABQgMgBgGgFg");
	this.shape_20.setTransform(70.5,41.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgSAuQgFAAAAgEIAAhWIALAAIAEABIABADIABAIQAEgFAGgEQAGgEAIAAIAFABIABADIAAAMIgDAAIgCAAQgHAAgGADQgGACgFAFIAABBg");
	this.shape_21.setTransform(60.975,42.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgcAoQgHgIAAgNQAAgJADgGQACgEAFgEQAFgDAGgBQAHgCAHAAIASAAIAAgFQAAgKgFgEQgFgDgKAAIgPABIgIAAIgDgBIgBgCIAAgIIAOgEIAPgBQAKAAAHADQAHACAEAEQAEAEACAGQACAGAAAIIAAA8IgLAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAAAIgBgEIgBgFQgFAEgGAEQgHADgIABQgOgBgHgHgAgJAEQgEAAgCACIgDAGIgBAGQAAAIAEAEQAEAEAJAAQAGAAAFgDQAFgDAEgEIAAgWIgSAAQgGAAgDACg");
	this.shape_22.setTransform(52.875,42.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgdA1QgHgMAAgWQAAgZAJgLQAIgMASAAQAHAAAFACIAHADIAAgoIAPAAIACABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAB8IgLAAIgDgBQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIgBgFQgEAEgHAEQgGADgJAAQgPAAgIgMgAgHgNQgEACgCAEQgDAEgBAFIgBAQQAAARAEAIQADAHALAAQAGAAAFgCIAHgGIAAg2IgHgCIgIgBQgFAAgFACg");
	this.shape_23.setTransform(43.8,40.625);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgcAoQgHgIAAgNQAAgJADgGQACgEAFgEQAFgDAGgBQAHgCAHAAIASAAIAAgFQAAgKgFgEQgFgDgKAAIgPABIgIAAIgDgBIgBgCIAAgIIAOgEIAPgBQAKAAAHADQAHACAEAEQAEAEACAGQACAGAAAIIAAA8IgLAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAAAIgBgEIgBgFQgFAEgGAEQgHADgIABQgOgBgHgHgAgJAEQgEAAgCACIgDAGIgBAGQAAAIAEAEQAEAEAJAAQAGAAAFgDQAFgDAEgEIAAgWIgSAAQgGAAgDACg");
	this.shape_24.setTransform(30.975,42.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgSAuQgFAAAAgEIAAhWIALAAIAEABIABADIABAIQAEgFAGgEQAGgEAIAAIAFABIABADIAAAMIgDAAIgCAAQgHAAgGADQgGACgFAFIAABBg");
	this.shape_25.setTransform(23.825,42.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgcAoQgHgIAAgNQAAgJADgGQACgEAFgEQAFgDAGgBQAHgCAHAAIASAAIAAgFQAAgKgFgEQgFgDgKAAIgPABIgIAAIgDgBIgBgCIAAgIIAOgEIAPgBQAKAAAHADQAHACAEAEQAEAEACAGQACAGAAAIIAAA8IgLAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAAAIgBgEIgBgFQgFAEgGAEQgHADgIABQgOgBgHgHgAgJAEQgEAAgCACIgDAGIgBAGQAAAIAEAEQAEAEAJAAQAGAAAFgDQAFgDAEgEIAAgWIgSAAQgGAAgDACg");
	this.shape_26.setTransform(15.725,42.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgcA+QgFAAAAgEIAAg8IAAgVIABgWIgDAAQgEAAAAgEIAAgIIAHgBIAJgBIAKgBIAKgBQAKAAAJADQAIACAFAFQAGAGACAJQADAIAAAOQAAAXgIAMQgJALgRAAQgHAAgFgBIgJgEIAAAjgAgPguIAAA8IAIADIAIABQAFAAAEgBQAEgCADgEQACgDABgHIABgPIgBgPQgBgGgDgEQgDgEgFgCQgEgBgHAAIgGAAg");
	this.shape_27.setTransform(6.575,43.875);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.copy03, new cjs.Rectangle(0,27,281.8,48.3), null);


(lib.copy02 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgdAlQgJgMAAgZQAAgYAJgLQAJgMAUAAQAUAAAJAMQAKALAAAYQAAAZgKAMQgJALgUAAQgUAAgJgLgAgJgfQgDACgCAEQgDADgBAHQgBAHgBAIQABAKABAHQABAGADAEQACAEADABQAEACAFAAQAFAAAEgCQAEgBACgEIAEgKIABgRIgBgPIgEgKQgCgEgEgCQgEgBgFgBQgFABgEABg");
	this.shape.setTransform(218.6,61.05);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgIA1QgGgGAAgNIAAg2IgGAAQgFAAABgDIAAgKIALAAIAAgZIANAAQADAAABAFIAAAUIARAAIADABQAAAAABAAQAAAAAAABQAAAAAAABQAAAAAAAAIAAAKIgVAAIAAA2QAAAEABADQACADAFAAIAEAAIAFAAQAEAAAAAEIAAAJIgHABIgIAAQgMAAgGgFg");
	this.shape_1.setTransform(210.7,59.95);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAXAvIgEgBIgBgDIAAg4QAAgJgEgFQgEgEgHAAQgHAAgFADIgIAGIAABFIgOAAQgEAAAAgEIAAhXIALAAIADABIACAEIAAAFQAMgMAQAAQAPAAAGAJQAGAIAAAOIAAA+g");
	this.shape_2.setTransform(202.925,60.975);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgNAuQgHgDgFgGQgFgFgDgKQgCgIAAgNQAAgMACgKQADgJAFgFQAEgGAHgDQAHgDAJAAQAKAAAHADQAGADAEAFQAEAFABAHQACAHAAAIIgBAJIgBAHIg0AAIACAMQABAFADAEQADADAFABQAEACAIAAIANgCIAIAAQAEAAAAAEIAAAIQgEACgIAAQgHACgKAAQgJAAgIgCgAgHgfQgEACgCAEIgEAJIgBALIAlAAIAAgCIAAgDQAAgMgDgFQgEgGgKAAQgFAAgEACg");
	this.shape_3.setTransform(193.775,61.05);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgEA/QgEAAAAgEIAAhWIANAAQAEAAAAADIAABXgAgHgsQgDgCAAgGQAAgFADgDQACgCAFAAQAGAAADACQACADAAAFQAAAGgCACQgDACgGAAQgFAAgCgCg");
	this.shape_4.setTransform(187.275,59.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAvAvQgEAAAAgEIAAg4QAAgJgDgFQgEgEgHAAQgHAAgFAEIgJAGIABAJIAAA7IgNAAIgDgBIgBgDIAAg4QAAgJgEgFQgEgEgHAAQgHAAgFADIgIAGIAABFIgNAAQgFAAAAgEIAAhXIALAAIAEABIABAEIABAFQAFgFAHgEQAGgDAJAAQAIAAAGADQAFADAEAHQAEgFAHgEQAHgEALAAQANAAAHAIQAHAHAAAQIAAA+g");
	this.shape_5.setTransform(178.075,60.975);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgEA/QgEAAAAgEIAAhWIANAAQAEAAAAADIAABXgAgHgsQgDgCAAgGQAAgFADgDQACgCAFAAQAGAAADACQACADAAAFQAAAGgCACQgDACgGAAQgFAAgCgCg");
	this.shape_6.setTransform(168.775,59.35);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgdA1QgHgMAAgWQAAgZAJgLQAJgMARAAQAHAAAFACIAIADIAAgoIANAAIADABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAB8IgLAAIgDgBQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIgBgFQgEAEgGAEQgHADgIAAQgRAAgHgMgAgHgNQgEACgCAEQgDAEgBAFIgBAQQAAARAEAIQAEAHAKAAQAGAAAFgCIAIgGIAAg2IgHgCIgJgBQgGAAgEACg");
	this.shape_7.setTransform(162,59.275);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAXAvIgEgBIgBgDIAAg4QAAgJgEgFQgEgEgHAAQgHAAgFADIgIAGIAABFIgOAAQgEAAAAgEIAAhXIALAAIADABIACAEIAAAFQAMgMAQAAQAPAAAGAJQAGAIAAAOIAAA+g");
	this.shape_8.setTransform(152.725,60.975);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgNAuQgHgDgFgGQgFgFgDgKQgCgIAAgNQAAgMACgKQADgJAFgFQAEgGAHgDQAHgDAJAAQAKAAAHADQAGADAEAFQAEAFABAHQACAHAAAIIgBAJIgBAHIg0AAIACAMQABAFADAEQADADAFABQAEACAIAAIANgCIAIAAQAEAAAAAEIAAAIQgEACgIAAQgHACgKAAQgJAAgIgCgAgHgfQgEACgCAEIgEAJIgBALIAlAAIAAgCIAAgDQAAgMgDgFQgEgGgKAAQgFAAgEACg");
	this.shape_9.setTransform(143.575,61.05);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgSAuQgFAAAAgEIAAhWIALAAIAEABIABADIABAIQAEgFAGgEQAGgEAIAAIAFABIABADIAAAMIgDAAIgCAAQgHAAgGADQgGABgFAHIAABAg");
	this.shape_10.setTransform(136.275,61.05);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgSAuQgFAAAAgEIAAhWIALAAIAEABIABADIABAIQAEgFAGgEQAGgEAIAAIAFABIABADIAAAMIgDAAIgCAAQgHAAgGADQgGABgFAHIAABAg");
	this.shape_11.setTransform(126.375,61.05);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgcAlQgJgMAAgZQAAgYAJgLQAIgMAUAAQAUAAAJAMQAJALAAAYQAAAZgJAMQgJALgUAAQgUAAgIgLgAgIgfQgEACgDAEQgCADgBAHQgBAHAAAIQAAAKABAHQABAGACAEQADAEAEABQAEACAEAAQAFAAAEgCQAEgBADgEIADgKIABgRIgBgPIgDgKQgDgEgEgCQgEgBgFgBQgEABgEABg");
	this.shape_12.setTransform(118.2,61.05);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgcA9IgEgBQgDgCAAgDIAAgIIAEAAIADAAIAHgBQAEgBACgDIAFgFIAFgIQgGgKgFgMIgJgWIgHgXIgFgWIAPAAIADABIABACIAEASIADAQIAGAQIAHAUQAHgPAFgUQAEgTACgTIAOAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAABIABACIgBAFIgBAEQgDATgEAPQgFAPgFALQgGAPgFAKQgFAJgFAFQgFAGgFACQgGACgFAAg");
	this.shape_13.setTransform(109.125,62.65);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgcAoQgHgIAAgNQAAgJADgGQACgEAFgEQAFgDAGgBQAHgBAHAAIASAAIAAgHQAAgJgFgDQgFgEgKAAIgPABIgIAAIgDgBIgBgCIAAgIIAOgDIAPgBQAKAAAHACQAHACAEAEQAEAEACAGQACAGAAAHIAAA9IgLAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAAAIgBgEIgBgFQgFAFgGADQgHADgIAAQgOAAgHgHgAgJADQgEABgCADIgDAEIgBAHQAAAIAEAEQAEAEAJAAQAGAAAFgDQAFgDAEgDIAAgXIgSAAQgGAAgDABg");
	this.shape_14.setTransform(100.225,61.05);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAvAvQgEAAAAgEIAAg4QAAgJgDgFQgEgEgHAAQgHAAgFAEIgJAGIABAJIAAA7IgNAAIgDgBIgBgDIAAg4QAAgJgEgFQgEgEgHAAQgHAAgFADIgIAGIAABFIgNAAQgFAAAAgEIAAhXIALAAIAEABIABAEIABAFQAFgFAHgEQAGgDAJAAQAIAAAGADQAFADAEAHQAEgFAHgEQAHgEALAAQANAAAHAIQAHAHAAAQIAAA+g");
	this.shape_15.setTransform(88.725,60.975);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAXAvIgEgBIgBgDIAAg4QAAgJgEgFQgEgEgHAAQgHAAgFADIgIAGIAABFIgOAAQgEAAAAgEIAAhXIALAAIADABIACAEIAAAFQAMgMAQAAQAPAAAGAJQAGAIAAAOIAAA+g");
	this.shape_16.setTransform(73.175,60.975);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgVAsQgFgCgDgEQgDgEgCgGQgCgGABgHIAAg9IANAAIAEABQAAABAAAAQAAAAABAAQAAABAAAAQAAABAAAAIAAA4QAAAJAEAEQADAEAJAAQAFAAAGgDQAFgCADgEIAAhEIAOAAQAEAAABAEIAABXIgLAAIgEgBQAAgBgBAAQAAAAAAgBQAAAAAAgBQgBAAAAgBIgBgFQgKAMgRAAQgHAAgGgDg");
	this.shape_17.setTransform(63.75,61.175);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgcA9IgEgBQgDgCAAgDIAAgIIAEAAIADAAIAHgBQAEgBACgDIAFgFIAFgIQgGgKgFgMIgJgWIgHgXIgFgWIAPAAIADABIABACIAEASIADAQIAGAQIAHAUQAHgPAFgUQAEgTACgTIAOAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAABIABACIgBAFIgBAEQgDATgEAPQgFAPgFALQgGAPgFAKQgFAJgFAFQgFAGgFACQgGACgFAAg");
	this.shape_18.setTransform(51.125,62.65);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgcAlQgJgMAAgZQAAgYAJgLQAIgMAUAAQAUAAAJAMQAJALAAAYQAAAZgJAMQgJALgUAAQgUAAgIgLgAgIgfQgEACgDAEQgCADgBAHQgBAHAAAIQAAAKABAHQABAGACAEQADAEAEABQAEACAEAAQAFAAAEgCQAEgBADgEIADgKIABgRIgBgPIgDgKQgDgEgEgCQgEgBgFgBQgEABgEABg");
	this.shape_19.setTransform(38.55,61.05);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgFBAQgEgCgCgEQgCgDgBgGIgBgLIAAhmIAOAAIACABIABADIAABnQAAAFACABQACABAEAAIAEACQABAAAAAAQAAAAAAABQABAAAAABQAAAAAAABIAAAJIgGAAIgHABQgFAAgDgBg");
	this.shape_20.setTransform(31.825,59.25);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgEA/QgEAAAAgEIAAhWIANAAQAEAAAAADIAABXgAgHgsQgDgCAAgGQAAgFADgDQACgCAFAAQAGAAADACQACADAAAFQAAAGgCACQgDACgGAAQgFAAgCgCg");
	this.shape_21.setTransform(27.125,59.35);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgIA1QgGgGAAgNIAAg2IgGAAQgFAAABgDIAAgKIALAAIABgZIAMAAQADAAABAFIAAAUIARAAIADABQAAAAABAAQAAAAAAABQAAAAAAABQAAAAAAAAIAAAKIgVAAIAAA2QgBAEACADQACADAFAAIAEAAIAFAAQAEAAAAAEIAAAJIgIABIgHAAQgMAAgGgFg");
	this.shape_22.setTransform(21.95,59.95);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgHAvIgIAAIgHgCIgFgBIgDgCIgBgDIAAgIIANABIAOABQALAAAEgDQAEgDAAgHIgBgFIgDgEIgGgDIgIgCIgMgEQgFgBgEgCQgEgDgCgEQgCgFAAgHQAAgOAJgHQAIgGAPAAIAGAAIAHABIAHABIAEACIADACIABADIAAAIIgOgCIgLAAQgJAAgEADQgEACAAAGIABAGIADADIAGADIAIACIAMADIAJAEQADADADAEQACAFAAAHQAAAIgDAFQgCAGgFADQgEAEgGABQgHACgGAAg");
	this.shape_23.setTransform(14.875,61.075);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgNAuQgHgDgFgGQgFgFgDgKQgCgIAAgNQAAgMACgKQADgJAFgFQAEgGAHgDQAHgDAJAAQAKAAAHADQAGADAEAFQAEAFABAHQACAHAAAIIgBAJIgBAHIg0AAIACAMQABAFADAEQADADAFABQAEACAIAAIANgCIAIAAQAEAAAAAEIAAAIQgEACgIAAQgHACgKAAQgJAAgIgCgAgHgfQgEACgCAEIgEAJIgBALIAlAAIAAgCIAAgDQAAgMgDgFQgEgGgKAAQgFAAgEACg");
	this.shape_24.setTransform(6.475,61.05);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgHAWQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAgDIAHgRQgEgBgCgCQgCgDAAgEQAAgGADgCQADgDAFAAQAHAAACADQADACAAAGIgBAHIgEAJIgHAQg");
	this.shape_25.setTransform(248.7,45.025);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgdA1QgHgMAAgWQAAgZAJgLQAJgMASAAQAGAAAFACIAHADIAAgoIAPAAIADABQAAAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAB8IgLAAIgDgBQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBIgBgFQgEAEgHAEQgGADgJAAQgPAAgIgMgAgHgNQgEACgDAEQgCAEgBAFIgBAQQAAARAEAIQAEAHAKAAQAGAAAFgCIAHgGIAAg2IgHgCIgIgBQgGAAgEACg");
	this.shape_26.setTransform(241.7,38.625);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgcAoQgHgIAAgOQAAgIADgFQACgFAFgDQAFgEAGgBQAHgBAHgBIASAAIAAgFQAAgKgFgEQgFgDgKAAIgPABIgIABIgDgBIgBgEIAAgHIAOgEIAPgBQAKAAAHACQAHADAEAEQAEAEACAGQACAGAAAIIAAA8IgLAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBIgBgDIgBgFQgFAFgGADQgHAEgIAAQgOAAgHgIgAgJAEQgEABgCABIgDAGIgBAGQAAAIAEAEQAEAEAJAAQAGAAAFgDQAFgDAEgEIAAgWIgSAAQgGAAgDACg");
	this.shape_27.setTransform(232.475,40.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgdA1QgHgMAAgWQAAgZAJgLQAIgMATAAQAGAAAFACIAIADIAAgoIANAAIAEABQAAAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAB8IgLAAIgEgBQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBIgBgFQgEAEgGAEQgHADgIAAQgRAAgHgMgAgHgNQgEACgDAEQgCAEgBAFIgBAQQAAARAEAIQADAHALAAQAGAAAFgCIAIgGIAAg2IgHgCIgJgBQgFAAgFACg");
	this.shape_28.setTransform(223.4,38.625);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgEA/QgEAAAAgEIAAhXIANAAQAEAAAAAFIAABWgAgHgtQgDgBAAgGQAAgFADgCQACgDAFAAQAGAAADADQACACAAAFQAAAGgCABQgDADgGAAQgFAAgCgDg");
	this.shape_29.setTransform(216.775,38.7);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgSAuQgFAAAAgEIAAhXIALAAIAEABIABAEIABAIQAEgFAGgEQAGgEAIAAIAFABIABADIAAAMIgDAAIgCAAQgHAAgGACQgGACgFAGIAABBg");
	this.shape_30.setTransform(211.925,40.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgVAsQgFgCgDgEQgEgEgBgGQgCgGAAgHIAAg9IAPAAIACABQABAAAAABQAAAAABABQAAAAAAAAQAAABAAAAIAAA4QAAAJAEAEQAEAEAHAAQAHAAAFgDQAFgCADgEIAAhEIAOAAQAFAAgBAEIAABXIgLAAIgDgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIgBgFQgMAMgQAAQgIAAgFgDg");
	this.shape_31.setTransform(203.75,40.525);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgJA+IgHgBIgHgBIgFgBQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAAAAAIgBgDIAAgIIANABIAMABQAMAAAFgEQAFgDAAgKIAAgLQgFAEgFACQgFACgHAAQgJAAgGgEQgGgCgEgHQgEgGgBgHQgBgIAAgJQAAgOACgJQADgIAFgFQAGgGAIgCQAIgCAKAAIAPABIANABIAFABQABABAAAAQAAABABAAQAAABAAAAQAAABAAABIAAAHIgHAAIABAXIAAAWIAAAfQAAAQgJAIQgJAJgRAAgAgHguQgEABgDAEQgDAEgCAGQgBAFAAALIABANQABAGACADQACADAEACQAEACAEAAQAFAAAEgCIAIgEIAAg3IgGAAIgFAAIgLABg");
	this.shape_32.setTransform(194.575,41.95);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgNAtQgHgCgFgFQgFgGgDgJQgCgKAAgNQAAgMACgJQADgJAFgGQAEgFAHgDQAHgDAJAAQAKAAAHADQAGADAEAFQAEAFABAHQACAHAAAHIgBAKIgBAHIg0AAIACAMQABAFADADQADAEAFABQAEACAIgBIANgBIAIAAQAEAAAAAEIAAAHQgEACgIACQgHABgKAAQgJAAgIgDgAgHgfQgEACgCADIgEAJIgBAMIAlAAIAAgDIAAgCQAAgLgDgHQgEgFgKAAQgFAAgEACg");
	this.shape_33.setTransform(185.325,40.4);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgHAvIgIAAIgHgCIgFgBIgDgCIgBgDIAAgIIANABIAOABQALAAAEgDQAEgDAAgHIgBgFIgDgEIgGgDIgIgCIgMgEQgFgBgEgCQgEgDgCgEQgCgFAAgHQAAgOAJgHQAIgGAPAAIAGAAIAHABIAHABIAEACIADACIABADIAAAIIgOgCIgLAAQgJAAgEADQgEACAAAGIABAGIADADIAGADIAIACIAMADIAJAEQADADADAEQACAFAAAHQAAAIgDAFQgCAGgFADQgEAEgGABQgHACgGAAg");
	this.shape_34.setTransform(176.875,40.425);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgHAWQgBAAgBAAQAAAAgBAAQAAgBAAAAQgBgBAAAAIABgDIAHgRQgEgBgDgCQgBgDAAgEQAAgGADgCQADgDAFAAQAHAAACADQADACAAAGIgBAHIgFAJIgGAQg");
	this.shape_35.setTransform(167.05,45.025);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgcAoQgHgIAAgOQAAgIADgFQACgFAFgDQAFgEAGgBQAHgBAHgBIASAAIAAgFQAAgKgFgEQgFgDgKAAIgPABIgIABIgDgBIgBgEIAAgHIAOgEIAPgBQAKAAAHACQAHADAEAEQAEAEACAGQACAGAAAIIAAA8IgLAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBIgBgDIgBgFQgFAFgGADQgHAEgIAAQgOAAgHgIgAgJAEQgEABgCABIgDAGIgBAGQAAAIAEAEQAEAEAJAAQAGAAAFgDQAFgDAEgEIAAgWIgSAAQgGAAgDACg");
	this.shape_36.setTransform(160.175,40.4);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgEA/QgEAAAAgEIAAhXIANAAQAEAAAAAFIAABWgAgHgtQgDgBAAgGQAAgFADgCQACgDAFAAQAGAAADADQACACAAAFQAAAGgCABQgDADgGAAQgFAAgCgDg");
	this.shape_37.setTransform(153.825,38.7);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgKAtQgHgEgFgGQgEgGgCgJQgCgIAAgMQABgYAIgLQAJgMARAAIANABIAJACIACADIABADIAAAIIgLgBIgJgBQgGAAgEACQgDABgDAEQgDAEgBAGQgBAGgBAJQABAKABAGQACAHADADQACAEADABQAEACAFAAIAKgBIAHgBQAEAAAAAFIAAAHIgKADQgHACgHAAQgJAAgHgDg");
	this.shape_38.setTransform(148.15,40.425);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AAXAvIgEgBIgBgDIAAg4QAAgJgEgFQgEgEgHAAQgHAAgFADIgIAGIAABFIgOAAQgEAAAAgEIAAhXIALAAIADABIACAEIAAAFQAMgMAQAAQAPAAAGAJQAGAIAAAOIAAA+g");
	this.shape_39.setTransform(139.525,40.325);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgNAtQgHgCgFgFQgFgGgDgJQgCgKAAgNQAAgMACgJQADgJAFgGQAEgFAHgDQAHgDAJAAQAKAAAHADQAGADAEAFQAEAFABAHQACAHAAAHIgBAKIgBAHIg0AAIACAMQABAFADADQADAEAFABQAEACAIgBIANgBIAIAAQAEAAAAAEIAAAHQgEACgIACQgHABgKAAQgJAAgIgDgAgHgfQgEACgCADIgEAJIgBAMIAlAAIAAgDIAAgCQAAgLgDgHQgEgFgKAAQgFAAgEACg");
	this.shape_40.setTransform(130.375,40.4);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgIA1QgGgGAAgMIAAg2IgGAAQgFAAABgFIAAgKIALAAIABgXIAMAAQADAAABADIAAAUIARAAIADABQAAABABAAQAAAAAAABQAAAAAAABQAAAAAAABIAAAKIgVAAIAAA1QgBAFACADQACACAFAAIAEAAIAFAAQAEAAAAAEIAAAIIgIACIgHABQgMAAgGgGg");
	this.shape_41.setTransform(122.75,39.3);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgdAkQgIgLgBgZQABgYAIgMQAKgLATAAQAUAAAJALQAJAMAAAYQAAAZgJALQgJAMgUAAQgTAAgKgMgAgIgfQgEABgCAEQgDAFgBAGQgCAHAAAIQAAAKACAGQABAHADAEQACAEAEABQAEACAEAAQAFAAAEgCQAEgBACgEIAEgLIABgQIgBgPIgEgLQgCgEgEgBQgEgBgFAAQgEAAgEABg");
	this.shape_42.setTransform(114.95,40.4);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgcA+QgFAAAAgEIAAg8IAAgVIABgWIgDAAQgEAAAAgEIAAgIIAHgBIAJgBIAKgBIAKgBQAKAAAJADQAIACAFAFQAGAGACAJQADAIAAAOQAAAXgIAMQgJALgRAAQgHAAgFgBIgJgEIAAAjgAgPguIAAA8IAIADIAIABQAFAAAEgBQAEgCADgEQACgDABgHIABgPIgBgPQgBgGgDgEQgDgEgFgCQgEgBgHAAIgGAAg");
	this.shape_43.setTransform(105.375,41.875);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AAXAvIgEgBIgBgDIAAg4QAAgJgEgFQgEgEgHAAQgHAAgFADIgIAGIAABFIgOAAQgEAAAAgEIAAhXIALAAIADABIACAEIAAAFQAMgMAQAAQAPAAAGAJQAGAIAAAOIAAA+g");
	this.shape_44.setTransform(92.525,40.325);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AgcAkQgJgLAAgZQAAgYAJgMQAIgLAUAAQAUAAAJALQAJAMAAAYQAAAZgJALQgJAMgUAAQgUAAgIgMgAgIgfQgEABgDAEQgCAFgBAGQgBAHAAAIQAAAKABAGQABAHACAEQADAEAEABQAEACAEAAQAFAAAEgCQAEgBADgEIADgLIABgQIgBgPIgDgLQgDgEgEgBQgEgBgFAAQgEAAgEABg");
	this.shape_45.setTransform(83.1,40.4);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgKAtQgHgEgFgGQgEgGgCgJQgCgIAAgMQAAgYAJgLQAJgMARAAIAMABIAJACIADADIABADIAAAIIgLgBIgJgBQgGAAgEACQgEABgCAEQgDAEgBAGQgBAGgBAJQABAKABAGQACAHADADQACAEADABQAEACAFAAIAKgBIAHgBQAEAAABAFIAAAHIgLADQgHACgHAAQgJAAgHgDg");
	this.shape_46.setTransform(74.7,40.425);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AgSAuQgFAAAAgEIAAhXIALAAIAEABIABAEIABAIQAEgFAGgEQAGgEAIAAIAFABIABADIAAAMIgDAAIgCAAQgHAAgGACQgGACgFAGIAABBg");
	this.shape_47.setTransform(64.325,40.4);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AgcAoQgHgIAAgOQAAgIADgFQACgFAFgDQAFgEAGgBQAHgBAHgBIASAAIAAgFQAAgKgFgEQgFgDgKAAIgPABIgIABIgDgBIgBgEIAAgHIAOgEIAPgBQAKAAAHACQAHADAEAEQAEAEACAGQACAGAAAIIAAA8IgLAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBIgBgDIgBgFQgFAFgGADQgHAEgIAAQgOAAgHgIgAgJAEQgEABgCABIgDAGIgBAGQAAAIAEAEQAEAEAJAAQAGAAAFgDQAFgDAEgEIAAgWIgSAAQgGAAgDACg");
	this.shape_48.setTransform(56.225,40.4);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgIA1QgGgGAAgMIAAg2IgGAAQgFAAAAgFIAAgKIAMAAIABgXIAMAAQAEAAAAADIAAAUIARAAIADABQAAABABAAQAAAAAAABQAAAAAAABQAAAAAAABIAAAKIgVAAIAAA1QAAAFABADQABACAFAAIAFAAIAEAAQAGAAgBAEIAAAIIgIACIgHABQgMAAgGgGg");
	this.shape_49.setTransform(48.75,39.3);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AAXAvIgEgBIgBgDIAAg4QAAgJgEgFQgEgEgHAAQgHAAgFADIgIAGIAABFIgOAAQgEAAAAgEIAAhXIALAAIADABIACAEIAAAFQAMgMAQAAQAPAAAGAJQAGAIAAAOIAAA+g");
	this.shape_50.setTransform(40.975,40.325);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgcAkQgKgLABgZQgBgYAKgMQAIgLAUAAQAUAAAJALQAJAMAAAYQAAAZgJALQgJAMgUAAQgUAAgIgMgAgIgfQgEABgDAEQgCAFgBAGQgCAHABAIQgBAKACAGQABAHACAEQADAEAEABQADACAFAAQAFAAAEgCQAEgBADgEIADgLIABgQIgBgPIgDgLQgDgEgEgBQgEgBgFAAQgFAAgDABg");
	this.shape_51.setTransform(31.55,40.4);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgKAtQgHgEgFgGQgEgGgBgJQgDgIAAgMQABgYAIgLQAJgMARAAIANABIAJACIACADIABADIAAAIIgLgBIgJgBQgGAAgEACQgDABgDAEQgDAEgBAGQgCAGAAAJQAAAKACAGQACAHADADQACAEADABQAEACAFAAIAKgBIAHgBQAEAAAAAFIAAAHIgKADQgHACgHAAQgJAAgHgDg");
	this.shape_52.setTransform(23.15,40.425);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AgFA/QgEgBgCgEQgCgDgBgFIgBgMIAAhmIAOAAIACABIABADIAABmQAAAFACACQACABAEAAIAEABQABABAAAAQAAAAAAABQABAAAAABQAAAAAAABIAAAIIgGACIgHAAQgFAAgDgCg");
	this.shape_53.setTransform(13.625,38.6);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgcAoQgHgIAAgOQAAgIADgFQACgFAFgDQAFgEAGgBQAHgBAHgBIASAAIAAgFQAAgKgFgEQgFgDgKAAIgPABIgIABIgDgBIgBgEIAAgHIAOgEIAPgBQAKAAAHACQAHADAEAEQAEAEACAGQACAGAAAIIAAA8IgLAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBIgBgDIgBgFQgFAFgGADQgHAEgIAAQgOAAgHgIgAgJAEQgEABgCABIgDAGIgBAGQAAAIAEAEQAEAEAJAAQAGAAAFgDQAFgDAEgEIAAgWIgSAAQgGAAgDACg");
	this.shape_54.setTransform(6.325,40.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.copy02, new cjs.Rectangle(0,25,281.8,48.3), null);


(lib.copy01 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgHAvIgIAAIgHgCIgFgBIgDgCIgBgDIAAgIIANABIAOABQALAAAEgDQAEgDAAgHIgBgFIgDgEIgGgDIgIgCIgMgEQgFgBgEgCQgEgDgCgEQgCgFAAgHQAAgOAJgHQAIgGAPAAIAGAAIAHABIAHABIAEACIADACIABADIAAAIIgOgCIgLAAQgJAAgEADQgEACAAAGIABAGIADADIAGADIAIACIAMADIAJAEQADADADAEQACAFAAAHQAAAIgDAFQgCAGgFADQgEAEgGABQgHACgGAAg");
	this.shape.setTransform(231.825,38.075);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgNA/QgHgCgFgGQgFgGgDgIQgCgKAAgNQAAgMACgIQADgKAFgGQAEgFAHgDQAHgDAJAAQAKAAAHADQAGADAEAFQAEAFABAHQACAGAAAHIgBAKIgBAIIg0AAIACAMQABAFADADQADAEAFABQAEABAIAAIANAAIAIgBQAEAAAAAEIAAAHQgEACgIABQgHACgKAAQgJAAgIgDgAgHgNQgEACgCADIgEAIIgBAMIAlAAIAAgDIAAgCQAAgKgDgHQgEgFgKAAQgFAAgEACgAgEgmQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAAAABgBIAFgLIAFgLIAOAAQABAAABAAQAAAAABABQAAAAABAAQAAABAAAAIgBADIgCADIgPATg");
	this.shape_1.setTransform(223.425,36.25);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgIA1QgGgGAAgMIAAg2IgGAAQgFAAAAgFIAAgKIAMAAIABgXIAMAAQAEAAAAADIAAAUIARAAIADABQAAABABAAQAAAAAAABQAAAAAAABQAAAAAAABIAAAKIgVAAIAAA1QAAAEABAEQABACAGAAIAEAAIAFAAQAEAAAAAEIAAAIIgIACIgHABQgMAAgGgGg");
	this.shape_2.setTransform(215.8,36.95);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgHAvIgIAAIgHgCIgFgBIgDgCIgBgDIAAgIIANABIAOABQALAAAEgDQAEgDAAgHIgBgFIgDgEIgGgDIgIgCIgMgEQgFgBgEgCQgEgDgCgEQgCgFAAgHQAAgOAJgHQAIgGAPAAIAGAAIAHABIAHABIAEACIADACIABADIAAAIIgOgCIgLAAQgJAAgEADQgEACAAAGIABAGIADADIAGADIAIACIAMADIAJAEQADADADAEQACAFAAAHQAAAIgDAFQgCAGgFADQgEAEgGABQgHACgGAAg");
	this.shape_3.setTransform(208.725,38.075);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgNAtQgHgCgFgGQgFgGgDgIQgCgKAAgNQAAgLACgJQADgKAFgGQAEgFAHgDQAHgDAJAAQAKAAAHADQAGADAEAFQAEAFABAHQACAHAAAHIgBAKIgBAHIg0AAIACAMQABAFADADQADAEAFABQAEABAIAAIANAAIAIgBQAEAAAAAEIAAAHQgEACgIABQgHACgKAAQgJAAgIgDgAgHgfQgEACgCADIgEAJIgBAMIAlAAIAAgDIAAgCQAAgLgDgHQgEgFgKAAQgFAAgEACg");
	this.shape_4.setTransform(200.325,38.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgNAtQgHgCgFgGQgFgGgDgIQgCgKAAgNQAAgLACgJQADgKAFgGQAEgFAHgDQAHgDAJAAQAKAAAHADQAGADAEAFQAEAFABAHQACAHAAAHIgBAKIgBAHIg0AAIACAMQABAFADADQADAEAFABQAEABAIAAIANAAIAIgBQAEAAAAAEIAAAHQgEACgIABQgHACgKAAQgJAAgIgDgAgHgfQgEACgCADIgEAJIgBAMIAlAAIAAgDIAAgCQAAgLgDgHQgEgFgKAAQgFAAgEACg");
	this.shape_5.setTransform(187.825,38.05);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgVAsQgFgCgDgEQgEgEgBgGQgCgGAAgHIAAg9IAOAAIADABQABAAAAABQAAAAABABQAAAAAAAAQAAABAAAAIAAA4QAAAJAEAEQAEAEAHAAQAHAAAFgDQAFgCADgEIAAhEIAOAAQAFAAAAAEIAABXIgMAAIgDgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIgBgFQgMAMgQAAQgIAAgFgDg");
	this.shape_6.setTransform(178.65,38.175);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAUA+IgDgBIgCgDIAAghIgKAFQgFACgHAAQgRAAgHgLQgIgLAAgWQAAgOADgKQADgJAFgGQAFgFAJgCQAIgDAKAAIAQABIANACIAFABQAAAAABABQAAAAAAABQAAAAAAABQAAABAAABIAAAHIgGAAIAAAWIABAVIAABAgAgGgtQgFABgEAEQgCAEgCAGQgCAHAAAKQAAAJACAFQABAHACADQACAEADABQAEACAFAAQAFAAAFgCIAHgEIAAg6IgFAAIgGAAIgKABg");
	this.shape_7.setTransform(169.4,39.525);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgcAoQgHgIAAgOQAAgIADgFQACgFAFgDQAFgEAGgBQAHgBAHgBIASAAIAAgGQAAgJgFgEQgFgDgKAAIgPABIgIABIgDgBIgBgEIAAgHIAOgEIAPgBQAKABAHABQAHADAEAEQAEAEACAGQACAGAAAIIAAA8IgLAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBIgBgCIgBgGQgFAEgGAEQgHAEgIAAQgOAAgHgIgAgJAEQgEABgCACIgDAFIgBAGQAAAIAEAEQAEAEAJAAQAGAAAFgDQAFgDAEgDIAAgXIgSAAQgGAAgDACg");
	this.shape_8.setTransform(156.325,38.05);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgSAuQgFAAAAgEIAAhXIALAAIAEABIABAEIABAIQAEgFAGgEQAGgEAIAAIAFABIABADIAAAMIgDAAIgCAAQgHAAgGACQgGADgFAFIAABBg");
	this.shape_9.setTransform(149.175,38.05);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgNAtQgHgCgFgGQgFgGgDgIQgCgKAAgNQAAgLACgJQADgKAFgGQAEgFAHgDQAHgDAJAAQAKAAAHADQAGADAEAFQAEAFABAHQACAHAAAHIgBAKIgBAHIg0AAIACAMQABAFADADQADAEAFABQAEABAIAAIANAAIAIgBQAEAAAAAEIAAAHQgEACgIABQgHACgKAAQgJAAgIgDgAgHgfQgEACgCADIgEAJIgBAMIAlAAIAAgDIAAgCQAAgLgDgHQgEgFgKAAQgFAAgEACg");
	this.shape_10.setTransform(141.275,38.05);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgEA/QgEAAAAgEIAAhXIANAAQAEAAAAAFIAABWgAgHgtQgDgCAAgFQAAgFADgCQACgDAFAAQAGAAADADQACACAAAFQAAAFgCACQgDADgGAAQgFAAgCgDg");
	this.shape_11.setTransform(134.775,36.35);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgUAsQgGgCgDgEQgEgEgBgGQgBgGgBgHIAAg9IAPAAIACABQABAAAAABQAAAAABABQAAAAAAAAQAAABAAAAIAAA4QAAAJAEAEQADAEAJAAQAFAAAGgDQAFgCADgEIAAhEIAOAAQAFAAgBAEIAABXIgLAAIgDgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIgCgFQgKAMgRAAQgIAAgEgDg");
	this.shape_12.setTransform(128.05,38.175);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAUA+IgEgBIgBgDIAAghIgKAFQgFACgHAAQgQAAgIgLQgHgLgBgWQABgOACgKQACgJAGgGQAGgFAIgCQAIgDALAAIAPABIANACIAFABQAAAAABABQAAAAAAABQAAAAAAABQABABAAABIAAAHIgHAAIAAAWIABAVIAABAgAgGgtQgFABgDAEQgDAEgCAGQgBAHgBAKQABAJABAFQABAHACADQACAEADABQAEACAFAAQAFAAAEgCIAIgEIAAg6IgFAAIgGAAIgKABg");
	this.shape_13.setTransform(118.8,39.525);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgNAtQgHgCgFgGQgFgGgDgIQgCgKAAgNQAAgLACgJQADgKAFgGQAEgFAHgDQAHgDAJAAQAKAAAHADQAGADAEAFQAEAFABAHQACAHAAAHIgBAKIgBAHIg0AAIACAMQABAFADADQADAEAFABQAEABAIAAIANAAIAIgBQAEAAAAAEIAAAHQgEACgIABQgHACgKAAQgJAAgIgDgAgHgfQgEACgCADIgEAJIgBAMIAlAAIAAgDIAAgCQAAgLgDgHQgEgFgKAAQgFAAgEACg");
	this.shape_14.setTransform(109.525,38.05);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgdA1QgHgMAAgWQAAgZAJgLQAIgMATAAQAGAAAFACIAIADIAAgoIAOAAIADABQAAAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAB8IgLAAIgEgBQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBIgBgFQgEAEgGAEQgHADgJAAQgPAAgIgMgAgHgNQgEACgDAEQgCAEgBAFIgBAQQAAARAEAIQAEAHAKAAQAGAAAFgCIAIgGIAAg2IgIgCIgIgBQgGAAgEACg");
	this.shape_15.setTransform(100.3,36.275);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAXAvIgEgBIgBgDIAAg4QAAgJgEgFQgEgEgHAAQgHAAgFADIgIAGIAABFIgOAAQgEAAAAgEIAAhXIALAAIADABIACAEIAAAFQAMgMAQAAQAPAAAGAJQAGAIAAAOIAAA+g");
	this.shape_16.setTransform(91.025,37.975);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgcAkQgKgLABgZQgBgYAKgMQAJgLATAAQAUAAAJALQAKAMgBAYQABAZgKALQgJAMgUAAQgTAAgJgMgAgJgfQgDABgDAEQgCAFgBAGQgCAGABAJQgBAKACAGQABAHACAEQADAEADACQAEABAFAAQAFAAAEgBQAEgCADgEIADgLIABgQIgBgPIgDgLQgDgEgEgBQgEgBgFAAQgFAAgEABg");
	this.shape_17.setTransform(81.6,38.05);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgdA1QgHgMAAgWQAAgZAJgLQAJgMARAAQAHAAAFACIAIADIAAgoIANAAIAEABQAAAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAB8IgLAAIgEgBQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBIgBgFQgEAEgGAEQgHADgIAAQgRAAgHgMgAgHgNQgEACgCAEQgDAEgBAFIgBAQQAAARAEAIQAEAHAKAAQAGAAAFgCIAIgGIAAg2IgHgCIgJgBQgFAAgFACg");
	this.shape_18.setTransform(72.1,36.275);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgHAvIgIAAIgHgCIgFgBIgDgCIgBgDIAAgIIANABIAOABQALAAAEgDQAEgDAAgHIgBgFIgDgEIgGgDIgIgCIgMgEQgFgBgEgCQgEgDgCgEQgCgFAAgHQAAgOAJgHQAIgGAPAAIAGAAIAHABIAHABIAEACIADACIABADIAAAIIgOgCIgLAAQgJAAgEADQgEACAAAGIABAGIADADIAGADIAIACIAMADIAJAEQADADADAEQACAFAAAHQAAAIgDAFQgCAGgFADQgEAEgGABQgHACgGAAg");
	this.shape_19.setTransform(59.925,38.075);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgcA6QgHgIAAgNQAAgJADgFQACgGAFgDQAFgEAGgBQAHgBAHAAIASAAIAAgGQAAgJgFgDQgFgEgKAAIgPABIgIABIgDgBIgBgDIAAgIIAOgDIAPgBQAKAAAHACQAHACAEAEQAEAEACAGQACAGAAAHIAAA9IgLAAQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAIgBgDIgBgGQgFAFgGADQgHAEgIAAQgOAAgHgIgAgJAWQgEABgCACIgDAFIgBAGQAAAIAEAEQAEAEAJAAQAGAAAFgDQAFgDAEgDIAAgXIgSAAQgGAAgDACgAgEgmQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAgBAAIABgDIAFgMIAFgLIAOAAQABAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAACIgCADIgPATg");
	this.shape_20.setTransform(51.325,36.225);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAvAvQgEAAAAgEIAAg4QAAgJgDgFQgEgEgHAAQgHAAgFAEIgJAGIABAJIAAA7IgNAAIgDgBIgBgDIAAg4QAAgJgEgFQgEgEgHAAQgHAAgFADIgIAGIAABFIgNAAQgFAAAAgEIAAhXIALAAIAEABIABAEIABAFQAFgFAHgEQAGgDAJAAQAIAAAGADQAFADAEAHQAEgFAHgEQAHgEALAAQANAAAHAIQAHAHAAAQIAAA+g");
	this.shape_21.setTransform(39.825,37.975);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgdAuQgEAAAAgEIAAgJIAKgPIAMgRIAMgQIAMgQIgpAAQgDAAAAgEIAAgKIA8AAQAEAAAAAFIAAAJIgMARIgOAPIgKAQIgKAOIArAAIADABIABADIAAALg");
	this.shape_22.setTransform(24.85,38.075);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgcAoQgHgIAAgOQAAgIADgFQACgFAFgDQAFgEAGgBQAHgBAHgBIASAAIAAgGQAAgJgFgEQgFgDgKAAIgPABIgIABIgDgBIgBgEIAAgHIAOgEIAPgBQAKABAHABQAHADAEAEQAEAEACAGQACAGAAAIIAAA8IgLAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBIgBgCIgBgGQgFAEgGAEQgHAEgIAAQgOAAgHgIgAgJAEQgEABgCACIgDAFIgBAGQAAAIAEAEQAEAEAJAAQAGAAAFgDQAFgDAEgDIAAgXIgSAAQgGAAgDACg");
	this.shape_23.setTransform(16.125,38.05);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAXBBIgEgBIgBgEIAAg5QAAgIgEgEQgEgEgHAAQgHAAgFADIgIAGIAABFIgOAAQgEAAAAgFIAAh7IAOAAIADABIABACIAAArQAFgFAHgDQAGgDAIAAQAPAAAGAIQAGAJAAANIAAA/g");
	this.shape_24.setTransform(7.125,36.2);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgHAWQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAgDIAHgRQgEgBgCgCQgCgDAAgEQAAgGADgCQADgDAFAAQAHAAACADQADACAAAGIgBAHIgEAJIgHAQg");
	this.shape_25.setTransform(144.75,21.025);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgiA/QgEAAAAgEIAAh2IASgCIASgBQAVAAAKAKQAKAJAAAVQAAAMgCAHQgDAIgFAEQgFAFgHADQgIACgJAAIgIgBIgLgCIAAAvgAgMgvIgHABIAAAvIAJACIAJABQAFAAAEgCQAFAAACgCQADgEACgEQABgGAAgIQAAgHgBgFQgCgFgDgEQgDgCgEgBQgFgCgEAAg");
	this.shape_26.setTransform(137.775,14.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAbA+IgDgBIAAgDIAAg0IguAAIAAA4IgPAAQgEAAAAgEIAAh3IAOAAIAEABIABADIAAAwIAuAAIAAg0IAOAAQAEAAAAAEIAAB3g");
	this.shape_27.setTransform(127.15,14.775);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgHAvIgIAAIgHgCIgFgBIgDgCIgBgDIAAgIIANABIAOABQALAAAEgDQAEgDAAgHIgBgFIgDgEIgGgDIgIgCIgMgEQgFgBgEgCQgEgDgCgEQgCgFAAgHQAAgOAJgHQAIgGAPAAIAGAAIAHABIAHABIAEACIADACIABADIAAAIIgOgCIgLAAQgJAAgEADQgEACAAAGIABAGIADADIAGADIAIACIAMADIAJAEQADADADAEQACAFAAAHQAAAIgDAFQgCAGgFADQgEAEgGABQgHACgGAAg");
	this.shape_28.setTransform(114.125,16.425);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgcAlQgKgMABgZQgBgYAKgLQAJgMATAAQAUAAAJAMQAKALgBAYQABAZgKAMQgJALgUAAQgTAAgJgLgAgJgfQgDABgDAFQgCAEgBAGQgCAHABAIQgBAKACAHQABAGACAEQADAEADABQAEACAFAAQAFAAAEgCQAEgBADgEIADgKIABgRIgBgPIgDgKQgDgFgEgBQgEgBgFAAQgFAAgEABg");
	this.shape_29.setTransform(105.45,16.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgcA+QgFAAAAgEIAAg8IAAgVIABgWIgDAAQgEAAAAgEIAAgIIAHgBIAJgBIAKgBIAKgBQAKAAAJADQAIACAFAFQAGAGACAJQADAIAAAOQAAAXgIAMQgJALgRAAQgHAAgFgBIgJgEIAAAjgAgPguIAAA8IAIADIAIABQAFAAAEgBQAEgCADgEQACgDABgHIABgPIgBgPQgBgGgDgEQgDgEgFgCQgEgBgHAAIgGAAg");
	this.shape_30.setTransform(95.875,17.875);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgEA/QgEAAAAgEIAAhWIANAAQAEAAAAADIAABXgAgHgsQgDgCAAgGQAAgFADgDQACgCAFAAQAGAAADACQACADAAAFQAAAGgCACQgDACgGAAQgFAAgCgCg");
	this.shape_31.setTransform(89.275,14.7);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgVAsQgFgCgDgEQgDgEgCgGQgBgGAAgHIAAg9IANAAIAEABQAAABAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAA4QAAAJAEAEQAEAEAHAAQAHAAAFgDQAFgCADgEIAAhEIAOAAQAEAAABAEIAABXIgLAAIgEgBQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAgBgBIAAgFQgLAMgRAAQgHAAgGgDg");
	this.shape_32.setTransform(82.55,16.525);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AAUA+IgDgBIgBgDIAAghIgKAFQgGACgHAAQgRAAgHgLQgIgLABgWQAAgOACgKQADgJAFgGQAGgFAIgCQAIgDAKAAIAPABIAOACIAFABQAAAAABABQAAAAAAABQAAAAAAABQAAABAAABIAAAHIgGAAIABAWIAAAVIAABAgAgHgtQgEABgEAEQgDAEgBAGQgBAHAAAKQAAAJABAFQABAHACADQACAEAEABQADACAFAAQAFAAAFgCIAIgEIAAg6IgGAAIgGAAIgLABg");
	this.shape_33.setTransform(73.3,17.875);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgNAuQgHgDgFgFQgFgHgDgJQgCgIAAgNQAAgMACgKQADgJAFgFQAEgHAHgCQAHgDAJAAQAKAAAHADQAGADAEAFQAEAFABAHQACAHAAAIIgBAJIgBAHIg0AAIACAMQABAFADAEQADADAFABQAEABAIAAIANgBIAIAAQAEAAAAAEIAAAIQgEACgIABQgHABgKAAQgJAAgIgCgAgHgfQgEACgCAEIgEAJIgBALIAlAAIAAgCIAAgDQAAgMgDgFQgEgGgKAAQgFAAgEACg");
	this.shape_34.setTransform(64.025,16.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgHAvIgIAAIgHgCIgFgBIgDgCIgBgDIAAgIIANABIAOABQALAAAEgDQAEgDAAgHIgBgFIgDgEIgGgDIgIgCIgMgEQgFgBgEgCQgEgDgCgEQgCgFAAgHQAAgOAJgHQAIgGAPAAIAGAAIAHABIAHABIAEACIADACIABADIAAAIIgOgCIgLAAQgJAAgEADQgEACAAAGIABAGIADADIAGADIAIACIAMADIAJAEQADADADAEQACAFAAAHQAAAIgDAFQgCAGgFADQgEAEgGABQgHACgGAAg");
	this.shape_35.setTransform(51.975,16.425);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgdAlQgIgMgBgZQABgYAIgLQAKgMATAAQAUAAAJAMQAKALAAAYQAAAZgKAMQgJALgUAAQgTAAgKgLgAgIgfQgEABgCAFQgDAEgBAGQgCAHAAAIQAAAKACAHQABAGADAEQACAEAEABQAEACAEAAQAFAAAEgCQAEgBACgEIAEgKIABgRIgBgPIgEgKQgCgFgEgBQgEgBgFAAQgEAAgEABg");
	this.shape_36.setTransform(43.3,16.4);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgFBAQgEgCgCgEQgCgDgBgGIgBgLIAAhmIAOAAIACABIABADIAABmQAAAGACABQACABAEAAIAEABQABABAAAAQAAAAAAABQABAAAAABQAAAAAAABIAAAJIgGABIgHAAQgFAAgDgBg");
	this.shape_37.setTransform(36.575,14.6);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AAXAvIgEgBIgBgDIAAg4QAAgJgEgFQgEgEgHAAQgHAAgFADIgIAGIAABFIgOAAQgEAAAAgEIAAhXIALAAIADABIACAEIAAAFQAMgMAQAAQAPAAAGAJQAGAIAAAOIAAA+g");
	this.shape_38.setTransform(25.625,16.325);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgdAlQgIgMgBgZQABgYAIgLQAJgMAUAAQAUAAAJAMQAKALAAAYQAAAZgKAMQgJALgUAAQgUAAgJgLgAgJgfQgDABgCAFQgDAEgBAGQgBAHgBAIQABAKABAHQABAGADAEQACAEADABQAFACAEAAQAFAAAEgCQAEgBACgEIAEgKIABgRIgBgPIgEgKQgCgFgEgBQgEgBgFAAQgEAAgFABg");
	this.shape_39.setTransform(16.2,16.4);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgMA9QgIgEgGgIQgFgIgCgMQgDgMAAgRQAAgQADgNQACgMAFgIQAGgHAIgEQAKgDALAAIANABIAKACIADADIABADIAAAJIgMgBIgMgBQgJAAgFACQgFACgEAGQgDAFgBAJQgCAJAAAOQAAAOACAKQACAJADAGQAEAFAFACQAFACAHAAIANgBIAIgBQAFAAAAAEIAAAJIgNAEQgHABgJAAQgLAAgJgDg");
	this.shape_40.setTransform(7.1,14.775);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#137AD4").s().p("EhL/AOQIAAt9ISzAAIAAQlgEha9AMKIAAr3IOaAAIAAN4gEBPdAH2QhrinAAk3QAAlQBvizQBvizDWAAQGYAAAAKYQAAFAhxCxQhxCyjRAAQjDAAhringEBQKAARQAAINEQABQEMAAAAoYQAAookHABQkVAAAAIxgEA2FAJlIAAifQBtBZCDAAQCxgBAAiBQAAg1gjggQgighh6g5Qh8g0gyg8Qgzg8AAhiQAAhzBdhOQBdhMCNAAQBtAABZArIAACVQhahCh4AAQhJAAgtAkQgtAlAAA4QAAA9AjAhQAkAiBqAtQCEA4A1A9QA1A9AABeQAAB4hcBLQhdBLiaAAQiDAAhig4gATxIaQh7iCAAjWQAAjlB+iFQB+iGDcABQDPAAB0CAQB1CBAADgQAADch9CHQh9CGjTAAQjNAAh7iDgAVhhPQhTBfAACtQAACmBUBeQBUBeCOAAQCQgBBNhbQBNheAAisQAAiuhNhdQhNhdiQAAQiQAAhTBggADLIfQhoh9AAjUQAAjlB0iLQBziLDBAAQC+AABYCWIAEAAIAAo9ICUAAIAAVaIiUAAIAAidIgEAAQhnC0jXAAQivAAhph+gAFKhMQhPBiAACwQAACgBKBcQBLBdB9AAQB7AABOhZQBPhZAAiJIAAiJQAAhxhNhNQhMhLhugBQiFABhPBigEBIUAKGIAAxeQgnAmhdAxQhbAvhNATIAAiWQBggaByg9QBxg8BFg+IA4AAIAAUsgEAuZAKGIjPrOIgDAAIjhLOIiUAAIkYudICcAAIDNLqIAHAAIDlrqICHAAIDPLqIAHAAIDKrqICTAAIkWOdgAjZKGIAAoPQAAkmjXAAQhtABhKBSQhKBTAACAIAAIPIiUAAIAAudICUAAIAACaIAEAAQBoiwDIAAQCYAABRBjQBQBkAAC1IAAI3gAy4KGIAAudICUAAIAAOdgA9UKGIkhwCIgEAAIkiQCIiwAAIl70QICmAAIEsQ6IAEAAIE5w6ICSAAIEpQ+IAEAAIEgw+IClAAIluUQgEhL/gAQIAAt/ISzioIAAQngEha9gAQIAAr6IOaiAIAAN6gAy0oAQgcgaAAgsQAAgnAbgcQAcgcApgBQAqAAAcAcQAcAcAAAoQAAAqgdAbQgdAcgoAAQgoAAgcgbg");
	this.shape_41.setTransform(214.986,-167.9845,0.1001,0.1001);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#0096D6").s().p("AgDChIAfhaIAtAAQAHgBAFgDQAFgEACgGIAkhhQAFgLgHgKQgFgHgNgBIg/AAIhRDhQgbgFgWgPQgXgPgQgVQgRgVgKgZQgJgZAAgdQAAgaAJgaQAJgYAQgUQAQgVAUgPQAWgPAagGIhSDgIAhAAIAsh3IAaAAIgsB3IAjAAIAnhvQAEgLgGgKQgFgHgMgBIgdAAIAghbIAHAAQAhABAdANQAdALAXAXQAWAWANAcQAMAfAAAfQAAAhgMAeQgNAdgWAWQgXAWgdANQgdAMghAAgAAkAxIAjhhIAaAAIgjBhg");
	this.shape_42.setTransform(20.1036,-160.4766,1.0903,1.0903);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.copy01, new cjs.Rectangle(0.4,-178.8,272.90000000000003,229.10000000000002), null);


// stage content:
(lib._300x250_v1_090920 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Copys
	this.instance = new lib.copy01();
	this.instance.setTransform(148.6,206.95,1,1,0,0,0,136.6,24.9);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.instance_1 = new lib.copy02();
	this.instance_1.setTransform(105.8,204.65,1,1,0,0,0,140.8,38.5);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.instance_2 = new lib.copy03();
	this.instance_2.setTransform(105.8,204.65,1,1,0,0,0,140.8,38.5);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.instance_3 = new lib.LastFrame();
	this.instance_3.setTransform(150.15,128.5,1,1,0,0,0,134.9,113.8);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(23).to({_off:false},0).to({y:216.95,alpha:1},28,cjs.Ease.cubicOut).wait(49).to({x:151.35,y:217.05,alpha:0},6,cjs.Ease.cubicOut).to({_off:true},1).wait(295));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(119).to({_off:false},0).to({x:152.8,alpha:1},14,cjs.Ease.quartOut).wait(66).to({y:225.65,alpha:0},15,cjs.Ease.quartOut).to({_off:true},1).wait(187));
	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(216).to({_off:false},0).to({x:152.8,alpha:1},14,cjs.Ease.quartOut).wait(66).to({y:225.65,alpha:0},15,cjs.Ease.quartOut).to({_off:true},1).wait(90));
	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(335).to({_off:false},0).to({alpha:1},13,cjs.Ease.quintIn).wait(54));

	// Fondo
	this.instance_4 = new lib.fondo();
	this.instance_4.setTransform(-331.5,125,1,1,0,0,0,642.5,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(14).to({x:-257.5},26,cjs.Ease.quintOut).wait(67).to({x:42.5},20,cjs.Ease.quartOut).wait(87).to({x:342.5},20,cjs.Ease.quartOut).wait(79).to({x:642.5},21,cjs.Ease.quartOut).wait(68));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-824,124,2109,138.5);
// library properties:
lib.properties = {
	id: '81D11B9EC08744098646B75322C38F72',
	width: 300,
	height: 250,
	fps: 25,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/back01.jpg?1600711531849", id:"back01"},
		{src:"images/back02.jpg?1600711531849", id:"back02"},
		{src:"images/back03.jpg?1600711531849", id:"back03"},
		{src:"images/back04.jpg?1600711531849", id:"back04"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['81D11B9EC08744098646B75322C38F72'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;